### ISSUE TITLE
TypeError: r is not a function

### ISSUE THREAD

**Issue by 373794764** [pixijs/pixijs#10009]
### Current Behavior

20:39:22.221 TypeError: r is not a function
    at http://localhost:8081/static/js/pages-index-index6.js:12041:28
    at Array.forEach (<anonymous>)
    at Object.k [as extend] (http://localhost:8081/static/js/pages-index-index6.js:12040:7)
    at Object.ixDk (http://localhost:8081/static/js/pages-index-index6.js:79222:8)
    at __webpack_require__ (http://localhost:8081/static/js/index.js:854:30)
    at fn (http://localhost:8081/static/js/index.js:151:20)
    at Object.IjTV (http://localhost:8081/static/js/pages-index-index6.js:35674:13)
    at __webpack_require__ (http://localhost:8081/static/js/index.js:854:30)
    at fn (http://localhost:8081/static/js/index.js:151:20)
    at Object.CKhb (http://localhost:8081/static/js/pages-index-index6.js:27389:14) at static/js/index.js:978
20:39:22.231 [Vue warn]: Failed to resolve async component: function (resolve) {
  var component = {
    component: Promise.all(/*! require.ensure | pages-index-index6 */[__webpack_require__.e("pages-index-index4~pages-index-index6"), __webpack_require__.e("pages-index-index6")]).then((function () {
      return resolve(__webpack_require__(/*! S:/code/box/h5/pages/index/index6.vue */ "7DsK"));
    }).bind(null, __webpack_require__)).catch(__webpack_require__.oe),
    delay: __uniConfig['async'].delay,
    timeout: __uniConfig['async'].timeout
  };
  if (__uniConfig['async']['loading']) {
    component.loading = {
      name: 'SystemAsyncLoading',
      render: function render(createElement) {
        return createElement(__uniConfig['async']['loading']);
      }
    };
  }
  if (__uniConfig['async']['error']) {
    component.error = {
      name: 'SystemAsyncError',
      render: function render(createElement) {
        return createElement(__uniConfig['async']['error']);
      }
    };
  }
  return component;
}
Reason: TypeError: r is not a function

### Expected Behavior

import * as PIXI from 'pixi.js';
import 'pixi-spine';

### Steps to Reproduce

import * as PIXI from 'pixi.js';
import 'pixi-spine';

### Environment

- **`pixi.js` version**: *e.g. 7.3.2*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by bigtimebuddy** [comment]
Can you please provide a reproduction? This stack trace isn't clear that Pixi is causing the exception.

**Comment by 373794764** [comment]
"When I import the components 'import * as PIXI from 'pixi.js'; import 'pixi-spine';' and try to render the defined spine animation file, I encounter the following error:"20:39:22.221 TypeError: r is not a function
    at http://localhost:8081/static/js/pages-index-index6.js:12041:28
    at Array.forEach (<anonymous>)
    at Object.k [as extend] (http://localhost:8081/static/js/pages-index-index6.js:12040:7)
    at Object.ixDk (http://localhost:8081/static/js/pages-index-index6.js:79222:8)
    at __webpack_require__ (http://localhost:8081/static/js/index.js:854:30)
    at fn (http://localhost:8081/static/js/index.js:151:20)
    at Object.IjTV (http://localhost:8081/static/js/pages-index-index6.js:35674:13)
    at __webpack_require__ (http://localhost:8081/static/js/index.js:854:30)
    at fn (http://localhost:8081/static/js/index.js:151:20)
    at Object.CKhb (http://localhost:8081/static/js/pages-index-index6.js:27389:14) at static/js/index.js:978
20:39:22.231 [Vue warn]: Failed to resolve async component: function (resolve) {
  var component = {
    component: Promise.all(/*! require.ensure | pages-index-index6 */[__webpack_require__.e("pages-index-index4~pages-index-index6"), __webpack_require__.e("pages-index-index6")]).then((function () {
      return resolve(__webpack_require__(/*! S:/code/box/h5/pages/index/index6.vue */ "7DsK"));
    }).bind(null, __webpack_require__)).catch(__webpack_require__.oe),
    delay: __uniConfig['async'].delay,
    timeout: __uniConfig['async'].timeout
  };
  if (__uniConfig['async']['loading']) {
    component.loading = {
      name: 'SystemAsyncLoading',
      render: function render(createElement) {
        return createElement(__uniConfig['async']['loading']);
      }
    };
  }
  if (__uniConfig['async']['error']) {
    component.error = {
      name: 'SystemAsyncError',
      render: function render(createElement) {
        return createElement(__uniConfig['async']['error']);
      }
    };
  }
  return component;
}
Reason: TypeError: r is not a function



"My code is as follows:"
<template>
  <div ref="animationContainer" style="width: 800px; height: 600px;"></div>
</template>

<script>
import * as PIXI from 'pixi.js';
import 'pixi-spine';

export default {
  name: 'SpineAnimation',

  mounted() {
	  console.log("aaa")
    this.initPixiApp();
  },

  methods: {
    initPixiApp() {
      const app = new PIXI.Application({
        width: 800,
        height: 600,
        backgroundColor: 0x1099bb,
      });
      this.$refs.animationContainer.appendChild(app.view);

      app.loader
        .add('spineAnimation', '../../src/spine/monster_b_2.json')
        .load((loader, resources) => {
          const spineAnimation = new PIXI.spine.Spine(resources.spineAnimation.spineData);

          spineAnimation.x = app.screen.width / 2;
          spineAnimation.y = app.screen.height / 2;
          spineAnimation.scale.set(0.5);

          spineAnimation.state.setAnimation(0, 'animationName', true);

          app.stage.addChild(spineAnimation);
        });
    },
  },
};
</script>

<style scoped>
</style>


"pixi-spine": "^4.0.4",
    "pixi.js": "^7.3.2",

**Comment by Zyie** [comment]
Thanks for reporting this issue!

We haven’t received a minimal reproduction to help investigate, and since some time has passed, we’re going to close this for now to help keep the issue tracker focused.

Please feel free to open a new issue with a minimal example, and we’d be happy to take another look
