### ISSUE TITLE
Bug: Crashing on SVG file color parsing (v8.0.0-rc)

### ISSUE THREAD

**Issue by MattTreichelYeah** [pixijs/pixijs#10019]
### Current Behavior

I'm using PIXI.Assets.load to load some .svg files.

```PIXI.Assets.load(sources.map(source => ({ name: source, src: `img/${source}` })))```

Some examples of the errors the SVG parsing seems to throw:

Ex. 1:
```
Error: Unable to convert color url(#gridpattern)
    at _Color._normalize (http://localhost:3000/lib/pixi.js:1744:15)
    at set value [as value] (http://localhost:3000/lib/pixi.js:1474:14)
    at _Color.setValue (http://localhost:3000/lib/pixi.js:1446:18)
    at parseStyle (http://localhost:3000/lib/pixi.js:14057:40)
    at renderChildren (http://localhost:3000/lib/pixi.js:13886:48)
    at renderChildren (http://localhost:3000/lib/pixi.js:14001:7)
    at renderChildren (http://localhost:3000/lib/pixi.js:14001:7)
    at renderChildren (http://localhost:3000/lib/pixi.js:14001:7)
    at SVGParser (http://localhost:3000/lib/pixi.js:13881:5)
    at _GraphicsContext.svg (http://localhost:3000/lib/pixi.js:14550:7)
```
on this SVG:
```
<?xml version="1.0" encoding="utf-8"?>
<svg width="225" height="214" viewBox="0 0 223.9080047607422 212.75" xmlns="http://www.w3.org/2000/svg">
  <g>
    <title>background</title>
    <g display="none" overflow="visible" y="0" x="0" height="100%" width="100%" id="canvasGrid">
      <rect fill="url(#gridpattern)" stroke-width="0" y="0" x="0" height="100%" width="100%"/>
    </g>
  </g>
  <g>
    <title>Layer 1</title>
    <path id="svg_1" d="M 0.75 81.727 L 79.176 70.269 L 112.329 0.75 L 144.863 70.888 L 223.908 81.727 L 164.548 135.179 L 181.289 212.75 L 112.019 169.516 L 43.369 212.75 L 60.11 134.87 L 0.75 81.727 Z" style="stroke-width: 2px; fill: rgb(255,255,255);"/>
  </g>
</svg>
```

Ex. 2
```
Error: Unable to convert color  none
    at _Color._normalize (http://localhost:3000/lib/pixi.js:1744:15)
    at set value [as value] (http://localhost:3000/lib/pixi.js:1474:14)
    at _Color.setValue (http://localhost:3000/lib/pixi.js:1446:18)
    at parseStyle (http://localhost:3000/lib/pixi.js:14032:46)
    at renderChildren (http://localhost:3000/lib/pixi.js:13886:48)
    at renderChildren (http://localhost:3000/lib/pixi.js:14001:7)
    at SVGParser (http://localhost:3000/lib/pixi.js:13881:5)
    at _GraphicsContext.svg (http://localhost:3000/lib/pixi.js:14550:7)
    at Object.parse (http://localhost:3000/lib/pixi.js:14765:15)
    at http://localhost:3000/lib/pixi.js:6602:37
```
for this SVG:
```
<?xml version="1.0" encoding="utf-8"?>
<svg viewBox="71 146.59300231933594 20 21" width="1000px" height="1000px" xmlns="http://www.w3.org/2000/svg" xmlns:bx="https://boxy-svg.com">
  <circle style="fill: rgb(255, 137, 212);" cx="77.624" cy="152.664" r="5.605" transform="matrix(1.600731, 0.24301, -0.166899, 1.099371, -17.815136, -26.817137)"/>
  <path d="M 8.996 2.818 Q 8.996 1.69 10.838 2.818 L 20.22 8.562 Q 22.062 9.69 20.22 9.69 L 10.838 9.69 Q 8.996 9.69 8.996 8.562 Z" style="fill: rgb(255, 137, 212);" transform="matrix(0.9458, -0.324749, 0.324749, 0.9458, 67.139359, 150.74321)" bx:shape="triangle 8.996 1.69 13.066 8 0 0.141 1@1249392d"/>
  <path d="M 77.365 153.654 C 77.547 153.789 78.499 154.301 78.823 153.977 C 79.059 153.739 79.654 153.295 80.128 153.531 C 80.895 153.911 81.305 154.437 82.173 154.437 C 82.819 154.437 84.342 153.928 84.879 154.461 C 84.977 154.559 85.095 154.607 85.204 154.715 C 85.299 154.809 84.791 155.126 84.729 155.157 C 84.413 155.312 84.354 155.588 84.354 155.95 C 84.354 156.034 84.292 156.474 84.354 156.535 C 84.431 156.612 84.872 156.72 85.023 156.796 C 86.209 157.385 85.677 155.481 85.677 155.188 C 85.677 154.987 85.914 155.536 86.095 155.626 C 86.387 155.772 87.536 155.958 87.889 155.781 C 88.486 155.481 87.948 154.674 87.572 154.487 C 87.305 154.354 86.161 154.41 85.989 154.579 C 85.969 154.6 85.623 154.771 85.732 154.879 C 85.891 155.037 86.201 155.115 86.358 155.271 C 86.593 155.505 86.414 156.631 86.414 156.993 C 86.414 157.459 86.096 157.879 85.994 158.337 C 85.983 158.384 85.712 159.211 85.696 159.195 C 85.662 159.162 85.976 157.807 86.053 157.652 C 86.221 157.316 86.179 156.506 86.179 156.128 C 86.179 156.048 86.094 155.642 86.132 155.602 C 86.147 155.588 86.928 155.696 86.959 155.701 C 87.461 155.784 88.386 156.053 88.649 156.576 C 88.771 156.819 88.918 157.387 89.096 157.564" style="fill: none; stroke: rgb(69, 69, 69);"/>
  <path d="M 78.323 157.281 C 79.005 156.416 81.229 155.175 82.001 156.718 C 82.099 156.914 82.092 157.285 82.168 157.505 C 82.407 158.192 81.161 159.061 80.77 159.447 C 80.352 159.862 81.155 160.911 81.155 161.054" style="fill: none; stroke: rgb(69, 69, 69);"/>
  <circle style="fill: rgb(69, 69, 69);" cx="80.509" cy="161.427" r="0.94" transform="matrix(0.785217, 0, 0, 0.822805, 18.128256, 29.527763)"/>
</svg>
```

### Expected Behavior

The files to load without error.

### Steps to Reproduce

I think it may just be running `PIXI.Assets.load()` with some particular SVG images, using less basic color properties.

### Environment

- **`pixi.js` version**: 8.0.0-rc
- **Browser & Version**: Chrome 120
- **OS & Version**: macOS 14.2

**Comment by Zyie** [comment]
This should be fixed in the latest rc.2

**Comment by MattTreichelYeah** [comment]
@Zyie 

Does not seem to be?

<img width="894" alt="image" src="https://github.com/pixijs/pixijs/assets/6729569/78087fcb-0beb-4c85-aead-3cd2edb85833">

**Comment by MattTreichelYeah** [comment]
I re-tested this on v8.0.0-rc.6 and my SVGs seem to be displaying correctly now without further change and nothing is crashing. Thanks.

**Comment by eperezsecull** [comment]
@Zyie  this seems to be breaking for me. 

```typescript
import * as PIXI from 'pixi.js'

export const CompassSVG = new PIXI.Graphics().svg(`
<svg xmlns="http://www.w3.org/2000/svg" width="77" height="76" fill="none">
  <path fill="url(#a)" d="M28.227 17.735s1.815-6.456 5.536-8.036c3.75-1.59 8.096 6.86 6.685 7.63-1.412.77-2.34-3.992-5.324-5.052-3.65-1.31-2.087 7.817-6.897 5.458Z"/>
  <path fill="url(#b)" d="M66.623 43.349v.198s-.02.03-.02.051v.042C65.373 56.676 52.779 66.5 38.26 66.5c-.555 0-1.11 0-1.654-.042-13.874-.696-25.66-10.416-26.7-23.11-.988-12.183 8.107-23.056 21.467-25.967h.01a32.472 32.472 0 0 1 6.887-.738c.897 0 1.784.031 2.661.104 5.97.478 11.324 2.536 15.589 5.676.05.696.221 1.434.655 1.83.474.436 1.27.446 1.956.342a25.12 25.12 0 0 1 2.158 2.319c2.863 3.461 4.719 7.588 5.253 12.017a22.26 22.26 0 0 1 .08 4.418Z"/>
  <path fill="url(#c)" d="M66.754 42.32c-.04.405-.081.81-.131 1.216v.094c-1.715 12.464-13.128 21.747-26.206 21.747h-.685c-12.04-.301-22.465-8.493-24.885-19.71-.04-.229-.09-.457-.13-.675a23.074 23.074 0 0 1-.334-2.662c-.756-11.092 6.292-21.103 17.01-24.949h.01c1.22-.437 2.48-.79 3.771-1.05a26.56 26.56 0 0 1 5.566-.572c6.03 0 11.494 1.882 15.84 5.021 0 0-.02.136-.04.375 0 .104-.01.228-.01.363-.02.26-.02.572 0 .905.05.696.221 1.434.655 1.83.474.436 1.27.446 1.956.343.182-.032.353-.063.504-.105.131-.03.242-.062.343-.093.293-.083.484-.156.484-.156 2.46 2.692 4.305 5.873 5.354 9.366.1.344.202.676.282 1.02.03.062.03.124.05.176.051.218.102.447.142.676l.08.343c.424 2.09.555 4.272.374 6.486v.01Z"/>
  <path fill="url(#d)" d="M58.183 42.32c-.504 8.94-8.44 15.864-17.736 15.864-1.058 0-2.077-.094-3.085-.26-7.865-1.31-14.086-7.651-14.439-15.604-.272-6.279 3.167-11.955 8.601-15.042 2.672-1.529 5.798-2.402 9.145-2.402 10.224 0 18.059 8.026 17.514 17.444Z"/>
  <path fill="url(#e)" d="M54.2 42.819c-.383 8.503-7.874 15.105-16.737 15.105h-.09c-7.865-1.31-14.086-7.651-14.44-15.604-.272-6.279 3.167-11.955 8.601-15.042a17.531 17.531 0 0 1 5.858-.988c9.7 0 17.222 7.589 16.819 16.54l-.01-.011Z"/>
  <path fill="#07659B" d="M14.988 27.267s15.992-20.188 38.95-8.13c0 0-19.369-11.912-35.773 8.608 0 0-4.044 1.757-3.187-.478h.01Z"/>
  <path fill="#FF9000" d="M55.038 43.068c.09-1.87-6.04-.478-5.859.76.182 1.236 5.687 2.712 5.858-.76Z"/>
  <path fill="#2750B8" d="M49.18 43.827c.312-.561 1.774.811 3.488.977 1.714.167 2.067-.634 2.067-.634s0 1.476-1.3 1.944c-1.301.468-4.084-1.85-4.256-2.287Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <path fill="#fff" d="M50.45 43.214c-.595.53 1.593.686 2.46 0s-1.17-1.144-2.46 0Z" style="mix-blend-mode:soft-light"/>
  <path fill="#FF9000" d="M38.25 25.313c-3.247.27-.232 5.707.252 5.738.473.031 3.024-6.019-.253-5.738Z"/>
  <path fill="#2750B8" d="M39.64 28.67s-.826 2.1-1.31 1.83c-.494-.27-1.674-3.43-1.18-4.72.495-1.299-.907-.072-.705 1.872.201 1.923 1.573 3.607 2.057 3.825.473.208 1.139-2.806 1.139-2.806Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <path fill="#fff" d="M38.935 25.614c-1.24-.135.07 1.83.474 2.09.403.25.887-1.944-.474-2.09Z" style="mix-blend-mode:soft-light"/>
  <path fill="#FF9000" d="M22.984 43.152s4.386.27 4.668.956c.283.686-4.063 2.1-4.063 2.1s-.544-2.235-.605-3.056Z"/>
  <path fill="#2750B8" d="M27.652 44.108s-.463 1.008-4.134 1.85l.515 1.518s3.256-1.258 3.62-3.358v-.01Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <path fill="#fff" d="M24.134 43.38c-1.22.614 2.177 1.133 2.47.728.292-.405-1.997-.967-2.47-.728Z" style="mix-blend-mode:soft-light"/>
  <path fill="#FF9000" d="M39.248 58.11c-2.773 0-.333-4.532.201-4.646.535-.125 2.713 4.647-.201 4.647Z"/>
  <path fill="#2750B8" d="M39.117 53.776s-1.331 2.64-.787 3.659c.545 1.019 2.077.28 2.077.28s-.383.676-2.46.25c-2.077-.437 1.16-4.19 1.16-4.19h.01Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <path fill="#fff" d="M39.863 53.828c-.595-.229-.323 1.476.292 1.59.615.125-.292-1.59-.292-1.59Z" style="mix-blend-mode:soft-light"/>
  <path fill="#2750B8" d="M36.505 44.607c-.696-.364-3.77-7.61.575-14.387 2.43-3.774 1.654 3.659 2.017 6.954.352 3.243-2.592 7.422-2.592 7.422v.01Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <path fill="#2A2385" d="m37.09 41.394-1.059 1.258s-.826-13.94 2.854-14.917L37.08 41.384l.01.01Z"/>
  <path fill="#4B3FEA" d="M37.09 41.395s-.575-9.668 1.3-13.182c1.2-2.245 2.552 3.701 3.187 8.41.363 2.713.343 5.146.343 5.146s-2.138-2.09-4.84-.364l.01-.01Z"/>
  <path fill="#2A2385" d="M36.031 42.819s-.262-5.364.03-7.724c.293-2.38.847-3.4 1.019-3.472.171-.073-.131 6.902-.07 8.244.07 1.32.08 1.61.08 1.61l-1.069 1.332.01.01Z"/>
  <path fill="#fff" d="M37.897 30.136c-.414 1.903-.131 5.26 1.815 7.807 1.915 2.516 1.31-3.191.746-6.528-.575-3.389-1.866-4.47-2.551-1.279h-.01Z" opacity=".5" style="mix-blend-mode:soft-light"/>
  <path fill="#4B3FEA" d="M42.686 42.902a3.342 3.342 0 0 1-3.337 3.296 3.318 3.318 0 0 1-3.318-3.296 3.336 3.336 0 0 1 3.338-3.358 3.306 3.306 0 0 1 3.317 3.358Z"/>
  <path fill="#2750B8" d="M36.707 41.831c-.696.364-3.771 7.61.575 14.388 2.43 3.773 1.653-3.66 2.016-6.955.353-3.243-2.591-7.422-2.591-7.422v-.01Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <path fill="#236285" d="m37.292 45.044-1.18-1.425s-.696 14.107 2.984 15.084l-1.804-13.649v-.01Z"/>
  <path fill="#EA3F3F" d="M37.292 45.044s-.575 9.668 1.3 13.181c1.2 2.246 2.551-3.7 3.187-8.41.362-2.713.342-5.146.342-5.146s-2.137 2.09-4.84.364l.01.01Z"/>
  <path fill="#922719" d="M36.092 43.453s-.131 5.53.161 7.88c.292 2.38.847 3.4 1.018 3.472.172.073-.13-6.903-.07-8.244.07-1.32.08-1.61.08-1.61l-1.2-1.498h.01Z"/>
  <path fill="#fff" d="M38.088 56.302c-.413-1.902-.13-5.26 1.815-7.807 1.916-2.516 1.31 3.191.746 6.528-.575 3.39-1.865 4.47-2.55 1.28h-.01Z" opacity=".5" style="mix-blend-mode:soft-light"/>
  <path fill="#4B3FEA" d="M42.686 42.996c-.02 1.83-1.341 3.295-2.944 3.295s-2.914-1.466-2.924-3.295c0-1.85 1.31-3.358 2.954-3.358 1.644 0 2.944 1.507 2.924 3.358h-.01Z"/>
  <path fill="#AB5455" d="M37.433 41.51c-.212.914 3.912 2.037 4.678 2.224.767.187.333-2.932-1.421-3.587-1.765-.665-3.257 1.362-3.257 1.362Z" opacity=".2" style="mix-blend-mode:multiply"/>
  <path fill="#DDD" d="M41.657 43.11c-.01 1.123-.826 2.027-1.814 2.027-.989 0-1.795-.904-1.795-2.027 0-1.133.806-2.058 1.815-2.058 1.008 0 1.805.925 1.794 2.058Z"/>
  <path fill="#2A2385" d="M40.488 43.1c0 .395-.292.706-.635.706s-.626-.311-.626-.706c0-.395.283-.718.636-.718.353 0 .635.323.625.718Z"/>
  <path fill="#3B5392" d="M22.934 42.32c.03.821 7.955-7.412 16.858-8.192 8.944-.78 12.704 6.435 16.032 6.778 3.327.343-1.966-17.454-16.526-15.988C24.85 26.373 22.772 37.185 22.934 42.32Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <path fill="#fff" d="M41.335 25.614s10.698.28 15.185 10.458c0 0-6.363 3.337-10.598.998-4.295-2.37-4.577-11.456-4.577-11.456h-.01ZM26.271 49.462c2.753-1.633 10.557 5.353 10.607 7.183.05 1.82-9.488-2.058-10.607-7.183Z"/>
  <path fill="#B6D3FF" d="M66.25 40.781s-4.245 3.556-5.596-2.88c-1.412-6.673-10.749-20.551-28.747-11.393-17.14 8.722-5.414 25.157-7.179 25.199-1.684.042-8.691-1.497-9.901-6.05-.04-.229-.09-.458-.131-.676C13.204 33.276 21.028 18.9 40.93 16.747c.343-.042.696-.083 1.05-.104h.04c6.301-.53 11.01 1.466 14.509 4.522 0 .104-.01.229-.01.364-.02.26-.02.572 0 .904.05.697.221 1.435.655 1.83.474.436 1.27.447 1.956.343.182-.031.353-.063.504-.104.595.78 1.14 1.58 1.634 2.39l.02.022c4.003 6.58 4.96 13.878 4.96 13.878v-.01Z" style="mix-blend-mode:soft-light"/>
  <path fill="#3B5392" d="M20.13 60.45c-.12-.635 2.249-1.123 2.733-1.082.484.042 5.354 4.387 11.958 6.02 6.544 1.621-5.717 1.975-14.69-4.938Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <path fill="#B6D3FF" d="M13.597 53.578c-.726-.8-3.338-6.549-3.136-8.347.202-1.82 3.085-2.547 3.358-2.412.272.135 1.583 6.715 3.892 10.635 2.248 3.836-4.114.124-4.114.124Z" style="mix-blend-mode:soft-light"/>
  <path fill="#3B5392" d="M10.27 37.205c-.474 2.38 3.559 1.133 3.912.697.353-.437 1.411-5.364 2.319-7.121.907-1.778-2.4-.832-2.4-.832s-2.763 1.892-3.831 7.267v-.01Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <path fill="#3B5392" d="M66.744 42.32c-.03.426-.081.852-.141 1.268v.042C65.363 56.666 52.779 66.5 38.26 66.5c-.555 0-1.11-.01-1.654-.042l-.444-.654s1.402-.094 3.55-.416c4.496-.686 13.037-2.475 18.27-6.633 6.16-4.896 8.51-13.067 8.56-19.814.01-1.465-.121-2.848-.393-4.106a23.25 23.25 0 0 1 .595 7.506v-.021Z" opacity=".8" style="mix-blend-mode:multiply"/>
  <path fill="#2DCAFF" d="M63.426 46.935c-.635-3.45-6.382 2.37-12.513 8.015-5.928 5.468-22.484 8.348-14.236 10.178 5.243 1.164 29.21-4.782 26.76-18.203l-.01.01Z" opacity=".4" style="mix-blend-mode:multiply"/>
  <path fill="#81D2FF" d="M28.298 53.578s4.537 5.5 11.897 5.78c7.35.28 13.32-6.611 13.32-6.611s-6.12 5.364-13.078 5.426c-6.624.073-12.15-4.605-12.15-4.605l.01.01Z"/>
  <path fill="#fff" d="M42.353 58.506c-1.23-.208 2.228-1.112 3.368-1.3 1.14-.176.776 2.163-3.368 1.3ZM19.818 23.618c-.938 2.34 4.386-2.411 8.722-4.709 4.386-2.318-7.038.489-8.722 4.71Z"/>
  <path fill="url(#f)" d="M57.89 42.029c-.503 8.794-8.297 15.593-17.432 15.593-1.039 0-2.047-.083-3.035-.25-7.734-1.288-13.854-7.516-14.197-15.333-.272-6.175 3.116-11.747 8.45-14.793a18.082 18.082 0 0 1 8.983-2.36c10.053 0 17.746 7.89 17.222 17.153l.01-.01Z" opacity=".72" style="mix-blend-mode:screen"/>
  <path fill="#3B5392" d="M56.57 20.78s-.02.136-.04.375c0 .104.04-.51.04-.375-.645-.436-1.452-.426-2.178-.81-4.043-2.152-8.46-2.88-12.372-3.337-2.651-.312-5.04-.354-6.856-.312a26.554 26.554 0 0 1 5.566-.572c6.03 0 11.494 1.882 15.84 5.021v.01Z" opacity=".8" style="mix-blend-mode:multiply"/>
  <path fill="#fff" d="M24.96 37.538c-.393-2.672 2.31-5.489 3.822-6.06 1.512-.572-3.822 6.06-3.822 6.06Z"/>
  <path fill="#3B596E" d="M34.045 12.069c-.907-.218.907-1.882 2.158-1.57 1.25.302 2.339 2.682 1.936 3.368-.394.686-2.38-2.027-4.104-1.798h.01Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <path fill="#fff" d="M30.455 13.566c.101 1.195 3.49-2.256 4.659-2.942 1.17-.686-3.055-1.726-4.659 2.942Z" style="mix-blend-mode:soft-light"/>
  <path fill="#3B5392" d="M42.928 23.556c-4.689.582 6.725 1.34 11.817 8.306 4.91 6.705 4.991 4.325 4.991 4.325s-2.863-11.924-16.808-12.62v-.011Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <path fill="#005686" d="M15.634 50.564c-.02-2.287 2.772.051 3.72 2.39.958 2.34-2.813 1.861-3.72-2.39Z"/>
  <path fill="#275E91" d="M16.34 51.988c.665 1.08 2.228.675 2.57.696.343.02-1.18-2.703-2.349-2.973-1.17-.28-.595 1.674-.221 2.277Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <path fill="url(#g)" d="M17.126 53.506s1.048.894 1.825.686c.776-.208.403-1.237.403-1.237s.585 1.206.151 1.642c-.443.437-2.036-.707-2.38-1.091Z"/>
  <path fill="url(#h)" d="M56.57 20.78s2.672 2.9 3.902 3.462c0 0-1.593.946-3.095.624-1.513-.312-.797-4.096-.797-4.096l-.01.01Z"/>
  <path fill="#3B5392" d="M56.53 21.154s1.35.978 1.593 2.121c.242 1.133-.676 1.133-1.341.78-.666-.354-.252-2.9-.252-2.9Z" opacity=".5" style="mix-blend-mode:multiply"/>
  <defs>
    <linearGradient id="a" x1="28.227" x2="40.72" y1="13.815" y2="13.815" gradientUnits="userSpaceOnUse">
      <stop stop-color="#003B66"/>
      <stop offset="1" stop-color="#005593"/>
    </linearGradient>
    <linearGradient id="b" x1="9.836" x2="66.703" y1="41.571" y2="41.571" gradientUnits="userSpaceOnUse">
      <stop stop-color="#06659A"/>
      <stop offset="1" stop-color="#095ABA"/>
    </linearGradient>
    <linearGradient id="c" x1="28.217" x2="54.069" y1="62.591" y2="19.177" gradientUnits="userSpaceOnUse">
      <stop stop-color="#62D0FF"/>
      <stop offset=".985" stop-color="#17C7FF"/>
    </linearGradient>
    <linearGradient id="d" x1="40.558" x2="40.558" y1="58.184" y2="24.876" gradientUnits="userSpaceOnUse">
      <stop stop-color="#0A578F"/>
      <stop offset="1" stop-color="#2345BF"/>
    </linearGradient>
    <linearGradient id="e" x1="38.562" x2="38.562" y1="57.924" y2="26.28" gradientUnits="userSpaceOnUse">
      <stop stop-color="#E4F7FF"/>
      <stop offset="1" stop-color="#F3FDFF"/>
    </linearGradient>
    <linearGradient id="g" x1="17.126" x2="19.677" y1="53.828" y2="53.828" gradientUnits="userSpaceOnUse">
      <stop stop-color="#63B5CF"/>
      <stop offset="1" stop-color="#6DFFED"/>
    </linearGradient>
    <linearGradient id="h" x1="57.215" x2="58.83" y1="24.845" y2="22.133" gradientUnits="userSpaceOnUse">
      <stop stop-color="#48A3D6"/>
      <stop offset="1" stop-color="#2EB4FF"/>
    </linearGradient>
    <radialGradient id="f" cx="0" cy="0" r="1" gradientTransform="matrix(19.7422 0 0 20.3544 47.092 33.328)" gradientUnits="userSpaceOnUse">
      <stop offset=".02" stop-color="#F1F9FE"/>
      <stop offset="1"/>
    </radialGradient>
  </defs>
</svg>
`)

``` 

<img width="508" alt="image" src="https://github.com/user-attachments/assets/e30466df-1f94-4b72-847e-04b0db3d6e49">

## Environment

- `pixi.js` version: 8.2.5
- Chrome version: 126
- OS: MacOS 14.5
