### ISSUE TITLE
Bug: `testVideoFormat` breaks @pixi/node

### ISSUE THREAD

**Issue by UlyssesZh** [pixijs/pixijs#10045]
### Current Behavior

Commit 75cd36f introduced `testVideoFormat` in `@pixi/assets`, and it makes `@pixi/assets` incompatible with `@pixi/node` because it uses the DOM only object `document`.

### Expected Behavior

Expected Behavior.

### Steps to Reproduce

```shell
npm i @pixi/node
echo 'import * as PIXI from "@pixi/node"; await PIXI.Assets.init();' > test.mjs
node test.mjs
```
```
file:///home/ulysses/temp/test-pixi/node_modules/@pixi/assets/lib/detections/utils/testVideoFormat.mjs:3
  return inWorker ? !1 : document.createElement("video").canPlayType(mimeType) !== "";
                         ^

ReferenceError: document is not defined
    at testVideoFormat (file:///home/ulysses/temp/test-pixi/node_modules/@pixi/assets/lib/detections/utils/testVideoFormat.mjs:3:26)
    at Object.test (file:///home/ulysses/temp/test-pixi/node_modules/@pixi/assets/lib/detections/parsers/detectWebm.mjs:8:21)
    at AssetsClass._detectFormats (file:///home/ulysses/temp/test-pixi/node_modules/@pixi/assets/lib/Assets.mjs:300:49)
    at async AssetsClass.init (file:///home/ulysses/temp/test-pixi/node_modules/@pixi/assets/lib/Assets.mjs:30:166)
    at async file:///home/ulysses/temp/test-pixi/test.mjs:1:37

Node.js v20.10.0
```

### Environment

- **`pixi.js` version**: 7.3.3
- Node.js: 20.10.0

**Comment by bigtimebuddy** [comment]
As a workaround, the best bet is to uninstall the video detection plugins. This should probably be added to `@pixi/node`, will move this issue to that project.

```ts
import { extensions, detectMp4, detectWebm, detectMp4 } from '@pixi/node';

// Uninstall the video detection plugins for node
extensions.remove(detectMp4, detectWebm, detectMp4);
```
