### ISSUE TITLE
Bug: v8.0.0-rc.3 TypeError on Graphics.destroy() after Graphics.clear()

### ISSUE THREAD

**Issue by davidye** [pixijs/pixijs#10098]
### Current Behavior

https://www.pixiplayground.com/#/edit/2h-PpaVBITXVSuPZC963W

### Expected Behavior

Crash after calling Graphics.clear() and then Graphics.destroy()

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'forEach')
    at GraphicsPipe._removeBatchForRenderable (pixi.js:13926:48)
    at GraphicsPipe.destroyRenderable (pixi.js:13863:14)
    at Graphics.<anonymous> (pixi.js:13921:16)
    at Graphics.emit (pixi.js:458:38)
    at Graphics.destroy (pixi.js:3992:14)
    at Graphics.destroy (pixi.js:18829:15)
    at main (demo.js:22:10)
```

### Steps to Reproduce

See playground

### Environment

See playground

**Comment by SuperSodaSea** [comment]
This should have been fixed in [5c5805d](https://github.com/pixijs/pixijs/commit/5c5805d78268bf44448d09409fb8bde40a7e0c21#diff-b86b9e029123440918f3f63bbd689f0354b1fbf39a4aa7ba6e4d28c1155069af), I think.
