### ISSUE TITLE
Bug: TypeError: Cannot read properties of null (reading 'structureDidChange')

### ISSUE THREAD

**Issue by erikdubbelboer** [pixijs/pixijs#10400]
### Current Behavior

Game crashes at a random point it seems.

<img width="731" alt="Screenshot 2024-03-31 at 10 39 28" src="https://github.com/pixijs/pixijs/assets/522870/283a00b2-528c-4e39-8c90-9c25dd90f79e">

```
TypeError: Cannot read properties of null (reading 'structureDidChange')
 at updateTransformAndChildren (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/SharedSystems-c84fc809.js:1499:48)
 at updateRenderGroupTransforms (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/SharedSystems-c84fc809.js:1445:7)
 at RenderGroupSystem.render (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/SharedSystems-c84fc809.js:1569:7)
 at SystemRunner.emit (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js:10121:21)
 at WebGPURenderer.render (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js:10265:25)
 at _Application.render (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js:10595:19)
 at TickerListener.emit (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js:6049:18)
 at _Ticker.update (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js:6350:29)
 at _tick (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js:6159:14)
```

### Expected Behavior

No crashing.

### Steps to Reproduce

I haven't been able to reproduce this but it is affecting roughly 2% of the players of the game which is around 400 per day.

### Environment

- **`pixi.js` version**: *8.0.4*
- **Browser & Version**: *any browser*
- **OS & Version**: *any os*
- **Running Example**: https://poki.com/en/g/silly-sky

**Comment by GoodBoyDigital** [comment]
heya! for this bug - do you call destroy on container / sprites etc? 
My hunch is there is a destroyed thing still in the scene graph!

**Comment by erikdubbelboer** [comment]
Yes, it's constantly creates and destroys things. Any way I can help pinpoint this?

**Comment by GoodBoyDigital** [comment]
is there the possibility something is destroyed but then added to the scene?

**Comment by erikdubbelboer** [comment]
I don't think so. The patterns of creating and destroying objects are pretty simple, there is no reusing of objects at all.

**Comment by GoodBoyDigital** [comment]
hey, would it be possible to inspect the code? hit me up on DM on Pixi discord if you can! Cheers!

**Comment by erikdubbelboer** [comment]
@GoodBoyDigital the code is very messy. I don't think you'll be able to do much with it. I'm adding more debugging now to try and find out what could be triggering it so I can reproduce it. I'll let you know when I have more information.

**Comment by GoodBoyDigital** [comment]
hey @erikdubbelboer ! Following up here - let me know if there is anything i can look into to help here! want to squash this one once and for all!

**Comment by erikdubbelboer** [comment]
I think I found the issue on my end. It's weird that this didn't cause any issues on Pixi 7 before. But now that I fixed it a small percentage of players gets this new error instead. I'll close this issue as it isn't related to `structureDidChange` anymore it seems.
```
TypeError: Cannot read properties of null (reading '_x')
 at Sprite.updateLocalTransform (/index.js:5400:22)
 at updateTransformAndChildren (/SharedSystems-874c6e71.js:1484:13)
 at updateRenderGroupTransforms (/SharedSystems-874c6e71.js:1452:7)
 at RenderGroupSystem.render (/SharedSystems-874c6e71.js:1576:7)
 at SystemRunner.emit (/index.js:10168:21)
 at WebGLRenderer.render (/index.js:10312:25)
 at _Application.render (/index.js:10642:19)
 at TickerListener.emit (/index.js:6085:18)
 at _Ticker.update (/index.js:6386:29)
 at _tick (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/53cbb308-39ee-418a-bf46-d6f5398cece6/index.js:6195:14)
```
