### ISSUE TITLE
Bug: TypeError: Failed to execute 'shaderSource' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLShader'

### ISSUE THREAD

**Issue by erikdubbelboer** [pixijs/pixijs#10403]
### Current Behavior

```
TypeError: Failed to execute 'shaderSource' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLShader'.
 at compileShader (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/WebGLRenderer-48e6939f.js:1470:6)
 at generateProgram (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/WebGLRenderer-48e6939f.js:1704:24)
 at GlShaderSystem._createProgramData (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/WebGLRenderer-48e6939f.js:1839:34)
 at GlShaderSystem._getProgramData (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/WebGLRenderer-48e6939f.js:1835:56)
 at GlShaderSystem._setProgram (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/WebGLRenderer-48e6939f.js:1826:30)
 at GlShaderSystem.bind (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/WebGLRenderer-48e6939f.js:1771:10)
 at GlEncoderSystem.draw (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/WebGLRenderer-48e6939f.js:971:21)
 at FilterSystem.applyFilter (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/init-8b4cff62.js:529:22)
 at DisplacementFilter.apply (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js:9394:19)
 at FilterSystem.pop (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/init-8b4cff62.js:404:18)
```

### Expected Behavior

Not to crash.

### Steps to Reproduce

Unknown, haven't been able to reproduce. Affects around 70 players per day for this game.

### Environment

- **`pixi.js` version**: *8.0.4*
- **Browser & Version**: *Chrome up to 123*
- **OS & Version**: *Any mobile or tablet OS*
- **Running Example**: https://poki.com/en/g/silly-sky

**Comment by GoodBoyDigital** [comment]
hey there! do you have any info on the device / os for this one? 
thanks!

**Comment by tzachyrm** [comment]
We're getting this too.

```
TypeError: Failed to execute 'shaderSource' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLShader'.
  at compileShader (../node_modules/pixi.js/src/rendering/renderers/gl/shader/program/compileShader.ts:12:8)
  at generateProgram (../node_modules/pixi.js/src/rendering/renderers/gl/shader/program/generateProgram.ts:22:26)
  at GlShaderSystem._createProgramData (../node_modules/pixi.js/src/rendering/renderers/gl/shader/GlShaderSystem.ts:190:38)
  at GlShaderSystem._getProgramData (../node_modules/pixi.js/src/rendering/renderers/gl/shader/GlShaderSystem.ts:183:60)
  at generateShaderSyncCode (../node_modules/pixi.js/src/rendering/renderers/gl/shader/GenerateShaderSyncCode.ts:38:38)
```

Device is Alcatel 1B (2020)
Android 10
<img width="566" alt="image" src="https://github.com/pixijs/pixijs/assets/6254831/fae645d0-5763-4b59-8992-ec84da98d0f2">

**Comment by bigtimebuddy** [comment]
Searching online, it seems like this error can often accompany a context loss in WebGL. This can happen for a number of reasons, but perhaps out-of-memory? Does anyone have this device mentioned above that could confirm?

**Comment by erikdubbelboer** [comment]
It's indeed caused by a context loss. I can trigger it one in a while on https://dubbelboer.com/sillysky/ by running this line in the console:
```
document.getElementsByTagName('canvas')[0].getContext('webgl2').getExtension('WEBGL_lose_context').loseContext();
```

**Comment by aidevelopercode** [comment]
Hello

i have the same probleme here i try to use pixi js, video render cause problem this demo work fine on pixijs.com : https://pixijs.com/8.x/examples/sprite/video
but locally with nextjs i have issue : 

![image](https://github.com/pixijs/pixijs/assets/103365421/1f377af2-157f-4958-a381-bcb8efb0d444)

**Comment by aidevelopercode** [comment]
Hello devs, 
i fixed the pobleme by reset chrom flags, go to chrome://flags/ and reset to defaut params. 

i think it's a problem with an experimental chome parameters

**Comment by rnike** [comment]
Also facing this problem, the website on iOS keeps reloading and leads to "A problem repeatedly occurred". Is there any proper way to handle context lost using pixi@v8?

**Comment by rnike** [comment]
> Also facing this problem, the website on iOS keeps reloading and leads to "A problem repeatedly occurred". Is there any proper way to handle context lost using pixi@v8?

I discovered that, in my case, it's an OOM issue. Using `createImageBitmap` to generate large textures will cause the problem.

```
  /**
   * The maximum size for decoded GIF, PNG, and TIFF images is 3 megapixels for
   * devices with less than 256 MB RAM and 5 megapixels for devices with greater
   * or equal than 256 MB RAM.
   *
   * reference: https://discussions.apple.com/thread/4975106
   */
```

**Comment by brunocalou** [comment]
It's happening with me as well. I've successfully reproduced it using an emulator with Android 10 version. The canvas goes black and, at least on the emulator, it crashes the browser a few times. Sometimes this problem doesn't happen and it's possible to see the rendered content and interact with it.

https://github.com/user-attachments/assets/6595b1f6-16d4-46b7-bcfd-e5ba6606bc0e

**Comment by brunocalou** [comment]
I could not fix the issue but I've managed to handle it properly. I listen to the `webglcontextlost` event, destroy the app, dispose the rest of the game, and show a message to the user. In case the webgl context is back, I init the game again. Here's how it's done:

```typescript
import { Application, isWebGLSupported, isWebGPUSupported } from "pixi.js";

interface MyGameOptions {
  canvas: HTMLCanvasElement;
  onUpdateUI: () => void;
}

export class MyGame {
  private canvas: HTMLCanvasElement;
  private app?: Application;
  private onUpdateUI: () => void;
  isLoading = true;
  error?: "webgl-not-supported" | "device-error";

  constructor({ canvas, onUpdateUI }: MyGameOptions) {
    this.canvas = canvas;
    this.onUpdateUI = onUpdateUI;
    this.init();
  }

  private async init() {
    this.initListeners();
    this.isLoading = true;

    try {
      if (isWebGLSupported(true) || (await isWebGPUSupported())) {
        this.error = undefined;
      } else {
        this.error = "webgl-not-supported";
      }
    } catch (error) {
      this.error = "webgl-not-supported";
    }

    if (this.error) {
      this.isLoading = false;
      this.onUpdateUI();
      return;
    }

    try {
      this.app = new Application();

      await this.app.init({
        canvas: this.canvas,
        // ... options
      });
    } catch (error) {
      this.error = "device-error";
      this.isLoading = false;
      this.onUpdateUI();
      return;
    }

    // ... init the rest of the game
  }

  private onWebGLContextLost = (event: Event) => {
    event.preventDefault();
    this.dispose();
    this.error = "device-error";
    this.onUpdateUI();
  };

  private onWebGLContextRestored = (event: Event) => {
    this.init();
  };

  private initListeners() {
    this.canvas.addEventListener("webglcontextlost", this.onWebGLContextLost);
    this.canvas.addEventListener(
      "webglcontextrestored",
      this.onWebGLContextRestored
    );
  }

  async dispose() {
    this.canvas.removeEventListener(
      "webglcontextlost",
      this.onWebGLContextLost
    );
    this.canvas.removeEventListener(
      "webglcontextrestored",
      this.onWebGLContextRestored
    );

    try {
      this.app?.destroy(true);
    } catch (error) {
      // Ignore
    }

    /// ... dispose the rest of the game
  }
}
```
