### ISSUE TITLE
Bug: TypeError: Cannot read properties of null (reading 'uid')

### ISSUE THREAD

**Issue by erikdubbelboer** [pixijs/pixijs#10405]
### Current Behavior

```
TypeError: Cannot read properties of null (reading 'uid')
 at GpuRenderTargetSystem.getGpuRenderTarget (https://95.214.53.152/d113fd3b-6791-4b1f-bf1c-968475b2a24e/SharedSystems-c84fc809.js?__cpo=aHR0cHM6Ly83ZTQ4NTg1Ny02ODZlLTQ3ZjYtOTU4OC0xZGFjZjUzNjQyMWIucG9raS1nZG4uY29t:1293:51)
 at GpuRenderTargetSystem.bind (https://95.214.53.152/d113fd3b-6791-4b1f-bf1c-968475b2a24e/SharedSystems-c84fc809.js?__cpo=aHR0cHM6Ly83ZTQ4NTg1Ny02ODZlLTQ3ZjYtOTU4OC0xZGFjZjUzNjQyMWIucG9raS1nZG4uY29t:1141:34)
 at GpuRenderTargetSystem.push (https://95.214.53.152/d113fd3b-6791-4b1f-bf1c-968475b2a24e/SharedSystems-c84fc809.js?__cpo=aHR0cHM6Ly83ZTQ4NTg1Ny02ODZlLTQ3ZjYtOTU4OC0xZGFjZjUzNjQyMWIucG9raS1nZG4uY29t:1191:31)
 at GpuRenderTargetSystem.renderStart (https://95.214.53.152/d113fd3b-6791-4b1f-bf1c-968475b2a24e/SharedSystems-c84fc809.js?__cpo=aHR0cHM6Ly83ZTQ4NTg1Ny02ODZlLTQ3ZjYtOTU4OC0xZGFjZjUzNjQyMWIucG9raS1nZG4uY29t:1119:10)
 at SystemRunner.emit (https://95.214.53.152/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js?__cpo=aHR0cHM6Ly83ZTQ4NTg1Ny02ODZlLTQ3ZjYtOTU4OC0xZGFjZjUzNjQyMWIucG9raS1nZG4uY29t:10121:21)
 at WebGPURenderer.render (https://95.214.53.152/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js?__cpo=aHR0cHM6Ly83ZTQ4NTg1Ny02ODZlLTQ3ZjYtOTU4OC0xZGFjZjUzNjQyMWIucG9raS1nZG4uY29t:10264:30)
 at drawCircle (https://95.214.53.152/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js?__cpo=aHR0cHM6Ly83ZTQ4NTg1Ny02ODZlLTQ3ZjYtOTU4OC0xZGFjZjUzNjQyMWIucG9raS1nZG4uY29t:28593:16)
 at init$3 (https://95.214.53.152/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js?__cpo=aHR0cHM6Ly83ZTQ4NTg1Ny02ODZlLTQ3ZjYtOTU4OC0xZGFjZjUzNjQyMWIucG9raS1nZG4uY29t:28850:3)
 at https://95.214.53.152/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js?__cpo=aHR0cHM6Ly83ZTQ4NTg1Ny02ODZlLTQ3ZjYtOTU4OC0xZGFjZjUzNjQyMWIucG9raS1nZG4uY29t:42467:7
 at doTask (https://95.214.53.152/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js?__cpo=aHR0cHM6Ly83ZTQ4NTg1Ny02ODZlLTQ3ZjYtOTU4OC0xZGFjZjUzNjQyMWIucG9raS1nZG4uY29t:42536:31)
```

### Expected Behavior

Not to crash.

### Steps to Reproduce

Unknown, affects around 50 players per day for this game.

### Environment

- **`pixi.js` version**: *8.0.4*
- **Browser & Version**: *Chrome up to 123*
- **OS & Version**: *Any*
- **Running Example**: https://poki.com/en/g/silly-sky

**Comment by GoodBoyDigital** [comment]
Heya! this looks like it may be a destroyed texture being reused! Is that something that could happen on the game side? Cheers!

**Comment by erikdubbelboer** [comment]
Since webgpu is disabled I don't see this issue anymore. I'll try enabling webgpu again after the next release to see if it still happens and if I can pinpoint why.

**Comment by Zyie** [comment]
@erikdubbelboer has this been fixed in the latest release?

**Comment by erikdubbelboer** [comment]
I ran the `preference: 'webgpu'` build again for a day. It's less than 1% of the users, but they are still affected:
```
TypeError: Cannot read properties of null (reading 'uid')
 at ne.getGpuRenderTarget (/SharedSystems-56798426.js:1:26602)
 at ne.bind (/SharedSystems-56798426.js:1:24340)
 at ne.push (/SharedSystems-56798426.js:1:25218)
 at ne.renderStart (/SharedSystems-56798426.js:1:23924)
 at ei.emit (/index.js:1:115952)
 at Te.render (/index.js:1:117763)
 at /index.js:1:458416
 at Il (/index.js:1:458481)
 at /index.js:30:15597
 at s (/index.js:30:17910)
```

**Comment by diwash007** [comment]
I too am getting this when using DropShadowFilter from pixi-filters

**Comment by RichMie** [comment]
The same error occurs when using DropShadowFilters & BlurFilters from pixi-filters. I am guessing the other filters from pixi-filters doesn't work too.

Version:
Pixi.js: 8.4.1
Pixi-filters: 6.0.6

**Comment by yjgaia** [comment]
I'm experiencing the exact same error. I can't use any filters at all. Do we have any idea when this might be resolved?

**Comment by bigtimebuddy** [comment]
Can someone please make a minimal reproduction of this issue?

**Comment by Zyie** [comment]
Thanks for reporting this issue!

We haven’t received a minimal reproduction to help investigate, and since some time has passed, we’re going to close this for now to help keep the issue tracker focused.

Please feel free to open a new issue with a minimal example, and we’d be happy to take another look
