### ISSUE TITLE
Bug: RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true

### ISSUE THREAD

**Issue by erikdubbelboer** [pixijs/pixijs#10404]
### Current Behavior

```
RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
 at GpuBufferSystem.createGPUBuffer (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/WebGPURenderer-cc3732e7.js:172:40)
 at GpuBufferSystem.updateBuffer (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/WebGPURenderer-cc3732e7.js:149:60)
 at GpuEncoderSystem._setVertexBuffer (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/WebGPURenderer-cc3732e7.js:381:73)
 at GpuEncoderSystem.setGeometry (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/WebGPURenderer-cc3732e7.js:402:12)
 at GpuGraphicsAdaptor.execute (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/WebGPURenderer-cc3732e7.js:1956:13)
 at GraphicsPipe.execute (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/init-8b4cff62.js:1509:19)
 at executeInstructions (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/SharedSystems-c84fc809.js:1396:40)
 at RenderGroupSystem.render (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/SharedSystems-c84fc809.js:1583:5)
 at SystemRunner.emit (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js:10121:21)
 at WebGPURenderer.render (https://7e485857-686e-47f6-9588-1dacf536421b.poki-gdn.com/d113fd3b-6791-4b1f-bf1c-968475b2a24e/index.js:10265:25)
```

### Expected Behavior

Not to crash.

### Steps to Reproduce

Unknown, affects around 70 players of this game each day.

### Environment

- **`pixi.js` version**: *8.0.4*
- **Browser & Version**: *Chrome up to 123*
- **OS & Version**: *Any*
- **Running Example**: https://poki.com/en/g/silly-sky

**Comment by GoodBoyDigital** [comment]
hey @erikdubbelboer - i think this may trigger when a large line is drawn in the game?

**Comment by luizsidney** [comment]
I have been facing a similar issue,

When running my PixiJS application (it is a big application) in multiple browser tabs, both instances crash, leading to black screens. The following errors are observed in the browser console:

Tab 1:

```
Uncaught RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
    at E.createGPUBuffer (p-d9f190ca.js:1:4076)
    at E.updateBuffer (p-d9f190ca.js:1:3596)
    ...
```

Tab 2:

```
[Invalid CommandBuffer] is invalid.
- While calling [Queue].Submit([[Invalid CommandBuffer]])
localhost/:1 A valid external Instance reference no longer exists.
localhost/:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
```

**Comment by Zyie** [comment]
Thanks for reporting this issue!

We haven’t received a minimal reproduction to help investigate, and since some time has passed, we’re going to close this for now to help keep the issue tracker focused.

Please feel free to open a new issue with a minimal example, and we’d be happy to take another look
