### ISSUE TITLE
Bug: Cannot read properties of null (reading 'append') TypeError: Cannot read properties of null (reading 'append')

### ISSUE THREAD

**Issue by Lfeier03** [pixijs/pixijs#10602]
### Current Behavior

在运行到 const GameScreen = new Container();
GameScreen.label = "GameScreen"
System().setCScreen(GameScreen);

// Create a new Graphics object
const graphics = new Graphics();  
后报错
buildContextBatches.ts:221  Uncaught TypeError: Cannot read properties of null (reading 'append')
    at eval (buildContextBatches.ts:221:1)
    at Proxy.forEach (<anonymous>)
    at addShapePathToGeometryData (buildContextBatches.ts:154:1)
    at buildContextBatches (buildContextBatches.ts:67:1)
    at Proxy.updateGpuContext (GraphicsContextSystem.ts:135:1)
    at Proxy.addRenderable (GraphicsPipe.ts:78:1)
    at collectAllRenderablesSimple (buildInstructions.ts:75:1)
    at collectAllRenderables (buildInstructions.ts:52:1)
    at collectAllRenderablesSimple (buildInstructions.ts:85:1)
    at collectAllRenderables (buildInstructions.ts:52:1)

### Expected Behavior

在屏幕左上角位置放置1个1000*1000的黑色矩形

### Steps to Reproduce

https://github.com/Lfeier03/staticWeb 暂时有问题的代码仓库地址
问题在  src/components/GameScreen.vue  实际上这个问题  会出现在整个项目中  

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*
Vue

**Comment by Lfeier03** [comment]
const basicText = new Text({ text: 'Basic text in pixi' });

basicText.x = 50;
basicText.y = 100;

GameScreen.addChild(basicText);
Uncaught TypeError: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLCanvasElement or HTMLImageElement or HTMLVideoElement or ImageBitmap or OffscreenCanvas or SVGImageElement or VideoFrame)'.
还有添加文本元素也会出现这种报错  在项目中任何位置都无法创建文本和图形

**Comment by Lfeier03** [comment]
问题解决了  我把pixi初始化代码和存储的对象数据 从pinia的状态库拿出来 单独放在ts中   解决了
