### ISSUE TITLE
Bug: SSR Issue: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by driuqzy** [pixijs/pixijs#10815]
### Current Behavior

SSR stopped working in latest dev commits.

I tested the following:

8.2.6 ✅ works 
8.2.6-dev.23656bd 🔴 broke
8.2.6-main.f2ad295 ✅ works 
8.2.5-main.83b7010 ✅ works 
8.2.5-dev.9c9b4eb 🔴 broke
8.2.5-main.416e6f1 ✅ works 
8.2.5-main.da00a52 🔴 broke
8.2.5-dev.6590194 🔴 broke
8.2.5-dev.6226362 ✅ works 
8.2.5 ✅ works 
8.2.4 ✅ works 
8.2.3 ✅ works 
8.2.2 ✅ works 
8.2.1 ✅ works 

```js
ReferenceError: document is not defined
    at Object.createCanvas (file:///project/workspace/node_modules/.pnpm/pixi.js@8.2.6-dev.23656bd/node_modules/pixi.js/src/environment-browser/BrowserAdapter.ts:21:24)
    at getTestContext (file:///project/workspace/node_modules/.pnpm/pixi.js@8.2.6-dev.23656bd/node_modules/pixi.js/src/rendering/renderers/gl/shader/program/getTestContext.ts:17:41)
    at getMaxTexturesPerBatch (file:///project/workspace/node_modules/.pnpm/pixi.js@8.2.6-dev.23656bd/node_modules/pixi.js/src/rendering/batcher/gl/utils/maxRecommendedTextures.ts:17:16)
    at file:///project/workspace/node_modules/.pnpm/pixi.js@8.2.6-dev.23656bd/node_modules/pixi.js/src/rendering/batcher/shared/Batcher.ts:127:22
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
    at run (/project/workspace/node_modules/.pnpm/@remix-run+serve@2.8.1_typescript@5.4.2/node_modules/@remix-run/serve/dist/cli.js:113:15)
```

### Expected Behavior

Pixi.js should not fail in SSR frameworks like Remix or Next.js.

### Steps to Reproduce

1. Create a new devbox using the official Remix template.
2. Add pixi.js as a dependency.
3. Try specific versions of pixi.js in package.json dependencies.
```
npm i
npm run dev
```

Here is a devbox using pixi.js `8.2.6-dev.23656bd` where you can see the 🔴 error in the terminal when you run `npm run dev`.
https://codesandbox.io/p/devbox/remix-pixi-ccnvrn

To fix, update package.json with a working pixi.js version and you will see it works. Here is a fork of the above, with the only change being package.json pixi.js `8.2.6`, which ✅ works:
https://codesandbox.io/p/devbox/remix-pixi-forked-3xg449?workspaceId=ff84f698-b1ab-4cc3-9c12-15ca7578ebd6

Btw the only pixi code is in app/routes/_index.tsx

### Environment

Remix

**Comment by Zyie** [comment]
thanks for flagging this! it seems that we are calling `getMaxTexturesPerBatch` in the static options for the `Batcher`

https://github.com/pixijs/pixijs/blob/2fd8897d8a141cd60ccb29df4ac411e9b9e7a2ca/src/rendering/batcher/shared/Batcher.ts#L127

we should do this as it doesn't allow for the `DOMAdpater` to be set up 

should be a simple enough fix

**Comment by Zyie** [comment]
@driuqzy can you test out this PR and see if it solves the issue for you. I don't have any SSR projects to test this on

you should be able to install this: `"pixi.js": "https://pkg.csb.dev/pixijs/pixijs/commit/0b641fc1/pixi.js",`

**Comment by driuqzy** [comment]
@Zyie Yes, I tested it on the devbox (https://codesandbox.io/p/devbox/remix-pixi-ccnvrn) and it works! ✅

Could you merge this fix to https://github.com/pixijs/pixijs/pull/10811 as that's what I was trying to test when I found the bug, thanks so much!
