### ISSUE TITLE
Bug: Crashing on SVG when use `new Graphics().svg()`

### ISSUE THREAD

**Issue by xmp-project** [pixijs/pixijs#10840]
### Current Behavior

i use `Graphics().svg`
```
const svg = new Graphics().svg(`
  <svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <radialGradient id="centerGradient" cx="50%" cy="50%" r="50%" fx="50%" fy="50%">
            <stop offset="0%" style="stop-color:rgb(0,0,0);stop-opacity:1" />
            <stop offset="100%" style="stop-color:rgb(255,255,255);stop-opacity:1" />
        </radialGradient>
    </defs>
    <rect  width="200" height="200" fill="url(#centerGradient)" />
</svg>
  `);
```
it report that:
```
Error: Unable to convert color url(#centerGradient)
    at _Color2._normalize (Color.ts:666:19)
    at set value (Color.ts:232:18)
    at _Color2.setValue (Color.ts:196:14)
    at parseStyle (SVGParser.ts:276:44)
    at renderChildren (SVGParser.ts:42:48)
    at renderChildren (SVGParser.ts:194:9)
    at SVGParser (SVGParser.ts:33:20)
    at _GraphicsContext2.svg (GraphicsContext.ts:846:9)
    at _Graphics._callContextMethod (Graphics.ts:200:37)
    at _Graphics.svg (Graphics.ts:597:21)
```
![image](https://github.com/user-attachments/assets/8c6d0b41-51ff-4ff4-a9fb-b0d9f4c50d6c)

### Expected Behavior

no error message

### Steps to Reproduce

```
const svg = new Graphics().svg(`
  <svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <radialGradient id="centerGradient" cx="50%" cy="50%" r="50%" fx="50%" fy="50%">
            <stop offset="0%" style="stop-color:rgb(0,0,0);stop-opacity:1" />
            <stop offset="100%" style="stop-color:rgb(255,255,255);stop-opacity:1" />
        </radialGradient>
    </defs>
    <rect  width="200" height="200" fill="url(#centerGradient)" />
</svg>
  `);
```

### Environment

- **`pixi.js` version**: *8.2.6*
- **Browser & Version**: * edge 127.0.2651.74 *
- **OS & Version**: *macOS 12.6.2*

**Comment by Zyie** [comment]
Thanks for raising this, however it appears to be a duplicate of #10106

If you feel this is not the same issue let us know and we can take another look
