### ISSUE TITLE
Bug: Fallback from WebGPU to WebGL doesn't occur in some instances, leading to complete rendering failure

### ISSUE THREAD

**Issue by xpluscal** [pixijs/pixijs#10906]
### Current Behavior

We have some users reporting complete rendering failure due to WebGPU errors (and not falling back to WebGL). This is for Linux, some Windows and some Mac users.

Log sample mac:
<img width="431" alt="Screenshot 2024-09-03 at 10 45 59" src="https://github.com/user-attachments/assets/d1ef253d-4f12-4529-a136-f0b200ba8b73">

Other log sample (windows):
`Uncaught RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
    at I.createGPUBuffer (WebGPURenderer.2eff5ac5.js:1:3294)
    at I.onBufferChange (WebGPURenderer.2eff5ac5.js:1:3522)
    at c.emit (IconBase.svelte_svel…fa7512ad.js:1:16655)
    at ts.setDataWithSize (IconBase.svelte_svel…a7512ad.js:968:8014)
    at ne.buildEnd (SharedSystems.feea39df.js:164:1353)
    at et (SharedSystems.feea39df.js:190:204)
    at be.render (SharedSystems.feea39df.js:309:9738)
    at xb.emit (0.1813efcc.js:1:4725)
    at Ye.render (0.1813efcc.js:1:6696)
    at ec.render (0.1813efcc.js:1:11798)
createGPUBuffer    @    WebGPURenderer.2eff5ac5.js:1
onBufferChange    @    WebGPURenderer.2eff5ac5.js:1
c.emit    @    IconBase.svelte_svel…_lang.fa7512ad.js:1
setDataWithSize    @    IconBase.svelte_svel…ang.fa7512ad.js:968
buildEnd    @    SharedSystems.feea39df.js:164
et    @    SharedSystems.feea39df.js:190
render    @    SharedSystems.feea39df.js:309
emit    @    0.1813efcc.js:1
render    @    0.1813efcc.js:1
render    @    0.1813efcc.js:1
emit    @    IconBase.svelte_svel…_lang.fa7512ad.js:6
update    @    IconBase.svelte_svel…_lang.fa7512ad.js:6
Qi._tick    @    IconBase.svelte_svel…_lang.fa7512ad.js:6`

### Expected Behavior

In case WebGPU fails, we would expect a fallback to WebGL (even with preference set to webgpu in init)

### Steps to Reproduce

Hard to reproduce, likely with large webgpu buffers.

### Environment

- **`pixi.js` version**: *8.3.4*
- **Browser & Version**: *Electron*
- **OS & Version**: *Linux / MacOS Sonoma / Windows 10*

### Possible Solution

Handle fallback gracefully to webgl.

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by GoodBoyDigital** [comment]
hey there! are you drawing somthing particularly complex in this situation? (like a large graphics?)

**Comment by xpluscal** [comment]
Hey @GoodBoyDigital depends on what you’d call complex. We’ve seen this issue happen for some users on older graphics cards (likely those without DirectX 12 support and hence no WebGPU support)

We’ve seen it fail as early as having 10-15 graphics rendered

**Comment by mreinstein** [comment]
I've run into this error too, but not using pixi and it seems to only affect my Linux user(s) so far.

**Comment by xingxing2008** [comment]
I also encountered the same issue. It occurs when rendering a large number of sprites (testing around 800-1000 sprites depend on ), resulting in an error. Could this be related to the GPU's video memory size?
```
WebGPURenderer-nJYgpi2B.js:1  Uncaught RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size (14384) is too large for the implementation when mappedAtCreation == true
    at W.createGPUBuffer (WebGPURenderer-nJYgpi2B.js:1:3163)
    at W.onBufferChange (WebGPURenderer-nJYgpi2B.js:1:3391)
    at Mf.a.emit (index-ASTrDjmO.js:2:66619)
    at _i.setDataWithSize (index-ASTrDjmO.js:28:7191)
    at he.buildEnd (SharedSystems-DzfRj6-D.js:170:2007)
    at Ce._buildInstructions (SharedSystems-DzfRj6-D.js:324:13147)
    at Ce._updateRenderGroups (SharedSystems-DzfRj6-D.js:324:12430)
    at Ce.render (SharedSystems-DzfRj6-D.js:324:10950)
    at ug.emit (index-ASTrDjmO.js:23:17812)
    at qe.render (index-ASTrDjmO.js:23:19935)
```
