### ISSUE TITLE
Bug: Text gradient fill doesn't work as written in documentation

### ISSUE THREAD

**Issue by sam007mac** [pixijs/pixijs#10926]
### Current Behavior

Text created with a fill as an array of strings throws an error, even though the documentation indicates that it should work.

### Expected Behavior

Text created with a fill as an array of strings should display as indicated in the documentation.

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/wQz19Pb9Mr73Rqr5VwXO6

There are two Text instances in the playground, one of which doesn't show due to the error. 
[The current documentation](https://pixijs.download/release/docs/text.html#TextStyleOptions) indicates that it should work.

### Environment

- **`pixi.js` version**: *8.x*
- **Browser & Version**: *Chrome*
- **OS & Version**: *Windows*
- **Running Example**: https://www.pixiplayground.com/#/edit/wQz19Pb9Mr73Rqr5VwXO6 

### Possible Solution

Preferred solution:
- pixijs is updated so that text fill gradients work as shown in the documentation.

Alternate solution:
- Documentation is updated to remove the issue.

**Comment by alexbown** [comment]
When in IDE it indicates that an array of strings is incorrect, but an array of numbers is ok, but still errors when ran.
e.g.
```        new TextStyle({
            fill: [0x00ff00, 0xff00ff]
        });```
Shows as valid syntax, but when ran in the pixi examples page an error is returned "Unable to convert color 00ff00,ff00ff".

**Comment by bigtimebuddy** [comment]
@Zyie I think `isColorLike` is being a little to greedy in checking for matches.

```
Uncaught (in promise) Error: Unable to convert color #000000,#FFFFFF
    at _Color._normalize (Color.ts:665:19)
    at set value (Color.ts:232:18)
    at _Color.setValue (Color.ts:195:22)
    at handleColorLike (convertFillInputToFillStyle.ts:47:31)
    at toFillStyle (convertFillInputToFillStyle.ts:172:16)
    at set fill (TextStyle.ts:418:22)
    at new _TextStyle (TextStyle.ts:280:29)
    at set style (AbstractText.ts:227:27)
    at new AbstractText (AbstractText.ts:114:22)
    at new Text (Text.ts:50:9)
```

We may want to check for `value instanceof Array && value.every(isColorLike)`. Also disambiguating from RGB Arrays like `[1, 1, 1]` might be a little tricky!

**Comment by GreenArrow18** [comment]
Is there a workaround for this? Can't find a way to make text gradients work in v8.
