### ISSUE TITLE
Using pixijs v6 with rollup

### ISSUE THREAD

**Issue by zcliu** [pixijs/pixijs#7513]
Hi,

I'm getting an error when using pixi.js with rollup. After installing pixi via npm, in the code I do: import * as PIXI from 'pixi.js'

I got the following error:

[!] Error: 'default' is not exported by node_modules/object-assign/index.js, imported by node_modules/@pixi/polyfill/dist/esm/polyfill.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/@pixi/polyfill/dist/esm/polyfill.js (9:7)
 7:  */
 8: import Polyfill from 'promise-polyfill';
 9: import objectAssign from 'object-assign';
           ^
10:
11: // Support for IE 9 - 11 which does not include Promises
Error: 'default' is not exported by node_modules/object-assign/index.js, imported by node_modules/@pixi/polyfill/dist/esm/polyfill.js
    at error (/Users/leozcliu/Code/Atlas/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/Users/leozcliu/Code/Atlas/node_modules/rollup/dist/shared/node-entry.js:9824:16)
    at handleMissingExport (/Users/leozcliu/Code/Atlas/node_modules/rollup/dist/shared/node-entry.js:9725:28)
    at Module.traceVariable (/Users/leozcliu/Code/Atlas/node_modules/rollup/dist/shared/node-entry.js:10163:24)
    at ModuleScope.findVariable (/Users/leozcliu/Code/Atlas/node_modules/rollup/dist/shared/node-entry.js:8770:39)
    at BlockScope.findVariable (/Users/leozcliu/Code/Atlas/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at Identifier$1.bind (/Users/leozcliu/Code/Atlas/node_modules/rollup/dist/shared/node-entry.js:4403:40)
    at AssignmentExpression.bind (/Users/leozcliu/Code/Atlas/node_modules/rollup/dist/shared/node-entry.js:3152:23)
    at ExpressionStatement$1.bind (/Users/leozcliu/Code/Atlas/node_modules/rollup/dist/shared/node-entry.js:3152:23)
    at BlockStatement$1.bind (/Users/leozcliu/Code/Atlas/node_modules/rollup/dist/shared/node-entry.js:3148:31)

Here's my rollup.config.js, it must be missing something?

```
export default [
    {
        input: "src/index.js",
        output: {
            file: "dist/myProject.js",
            name: "myProject",
            format: "umd"
        },
        plugins: [
            resolve()
        ],
        onwarn: function (warning, warn) {
            if (warning.code === 'CIRCULAR_DEPENDENCY') return;
            warn(warning);
        }
    }
];
```

Pixijs verison: 6.0.4, rollup version: 1.16

**Comment by eXponenta** [comment]
Yep.
Same problem.
I think we should remove non-esm polyfill from dependencies because it requires special rule in rolup.

**Comment by bigtimebuddy** [comment]
I created an example of using PixiJS v6 and Rollup to provide some guidance here:
https://github.com/bigtimebuddy/pixi-rollup-example

Many of our third-party dependencies use CommonJS bundles yet and do not have ESM-based bundles. So this is not as easy as swapping out a single dependency.

I'm going to close this issue. If you hit more snags with Rollup or other integrations, please create a discussion thread instead of an issue as it's outside the scope of code.
