### ISSUE TITLE
Setting a fontSize using a percentage throws an error

### ISSUE THREAD

**Issue by mimshwright** [pixijs/pixijs#8205]
It appears that setting fontSize to a percentage results in an object with no dimensions thus throwing an error. 

I discovered this in [my tagged-text component](https://github.com/mimshwright/pixi-tagged-text/issues/107), but it appears when you try this code in the [online examples](https://pixijs.io/examples/#/text/text.js). I even wrote a test case for it which also throws. 

Details below...

### Steps to reproduce
This test or 
```javascript
    it('Should allow setting font sizes using percentages', () =>
    {
        const app = new Application({ backgroundColor: 0x1099bb });

        document.body.appendChild(app.view);

        const style = new TextStyle({
            fontSize: '100%',
        });

        const richText = new Text('Text with fontSize: 100%', style);

        // In browser, this line throws an error.
        app.stage.addChild(richText);

        // In tests, accessing the height throws an error.  Why are these different? Maybe has to do with Ticker triggering renderer?
        expect(() => richText.height).to.not.throw(); 
        expect(richText.height).to.be(10);
    });
```

### Expected Behavior

Theoretically, any size values supported by [CanvasRenderingContext2D](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/font) should be supported for `fontSize`.

The [spec for CanvasRenderingContext2D](https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-font) describes how the percentages should be interpreted. 

> When the object implementing the [CanvasTextDrawingStyles](https://html.spec.whatwg.org/multipage/canvas.html#canvastextdrawingstyles) interface is created, the font of the context must be set to 10px sans-serif. When the ['font-size'](https://drafts.csswg.org/css-fonts/#font-size-prop) component is set to lengths **using percentages**, ['em'](https://drafts.csswg.org/css-values/#em) or ['ex'](https://drafts.csswg.org/css-values/#ex) units, or the 'larger' or 'smaller' keywords, **these must be interpreted relative to the [computed value](https://drafts.csswg.org/css-cascade/#computed-value) of the ['font-size'](https://drafts.csswg.org/css-fonts/#font-size-prop) property of the [font style source object](https://html.spec.whatwg.org/multipage/canvas.html#font-style-source-object) at the time that the attribute is set**, if it is an element ... If the [computed values](https://drafts.csswg.org/css-cascade/#computed-value) are undefined for a particular case (e.g. because the [font style source object](https://html.spec.whatwg.org/multipage/canvas.html#font-style-source-object) is not an element or is not [being rendered](https://html.spec.whatwg.org/multipage/rendering.html#being-rendered)), then **the relative keywords must be interpreted relative to the normal-weight 10px sans-serif default.**

### Current Behavior
Throws the following error (browser):

```
text.js:1187 Uncaught DOMException: Failed to execute 'getImageData' on 'OffscreenCanvasRenderingContext2D': The source width is 0.
    at Function.TextMetrics.measureFont (https://d157l7jdn8e5sf.cloudfront.net/dev/pixi-legacy.js:32612:35)
    at Function.TextMetrics.measureText (https://d157l7jdn8e5sf.cloudfront.net/dev/pixi-legacy.js:32230:44)
    at Text.updateText (https://d157l7jdn8e5sf.cloudfront.net/dev/pixi-legacy.js:32887:38)
    at Text._render (https://d157l7jdn8e5sf.cloudfront.net/dev/pixi-legacy.js:33075:16)
    at Text.Container.render (https://d157l7jdn8e5sf.cloudfront.net/dev/pixi-legacy.js:9585:20)
    at Container.render (https://d157l7jdn8e5sf.cloudfront.net/dev/pixi-legacy.js:9587:36)
    at Renderer.render (https://d157l7jdn8e5sf.cloudfront.net/dev/pixi-legacy.js:22699:25)
    at Application.render (https://d157l7jdn8e5sf.cloudfront.net/dev/pixi-legacy.js:23706:25)
    at TickerListener.emit (https://d157l7jdn8e5sf.cloudfront.net/dev/pixi-legacy.js:10361:27)
    at Ticker.update (https://d157l7jdn8e5sf.cloudfront.net/dev/pixi-legacy.js:10745:39)
```

### Possible Solution

I checked the source code for TextStyle and...

1. The value for fontSize ([src](https://github.com/pixijs/pixijs/blob/dev/packages/text/src/TextStyle.ts#L705))
- if the value is a number, "px" is appended to it
- if it's a string, it remains unchanged
2. It's passed directly to context.font ([src](https://github.com/pixijs/pixijs/blob/0f150cb709d35dc0c62ae3b48e1c1ecfb70bbbfc/packages/text-bitmap/src/utils/drawGlyph.ts#L40))

So theoretically, any string you provide should go directly to the context. So, I guess it's possible this is an upstream issue with Chromium's canvas/context? But it also could be related to the [font style source object](https://html.spec.whatwg.org/multipage/canvas.html#font-style-source-object) used internally by Pixi.

### Environment

- **`pixi.js` version**: v6.2.2 and has existed at least since v5.3.2
- **Browser & Version**: Brave (Chromium) [Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (x86_64)](https://brave.com/latest/) 
- **OS & Version**: MacOS 12.1

**Comment by bigtimebuddy** [comment]
I created a minimal reproduction without PixiJS: https://jsfiddle.net/bigtimebuddy/b0kzhefx/1/

Seems like OffscreenCanvas doesn't respect percentages (but a regular HTMLCanvasElement or pixel sizes are fine).

I think this actually makes a lot of sense conceptually, since OffscreenCanvas is not connected to the DOM (which would determine the baseline font size).

So not sure if this is a bug. 

I think the best thing we can do is offer some documentation warning around using percentages.
