### ISSUE TITLE
Async Test Fail Periodically

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixijs#8468]
We are having issues with this test and it's periodically breaking our GH Actions. Less familiar with this code, anyone have ideas?

https://github.com/pixijs/pixijs/blob/51b55fd3ed1c18f114e040b5da6806f103808d93/packages/loaders/test/AsyncQueue.tests.ts#L7-L67

### Example 

```
Summary of all failing tests
FAIL packages/loaders/test/AsyncQueue.tests.ts
  ● Test suite failed to run
      ● async › queue › basics
        expect(received).toEqual(expected) // deep equality
        - Expected  - 2
        + Received  + 2
          Array [
            "process 2",
            "callback 2",
            "process 1",
            "callback 1",
        -   "process 4",
        -   "callback 4",
            "process 3",
            "callback 3",
        +   "process 4",
        +   "callback 4",
          ]
          56 |             q.drain = () =>
          57 |             {
        > 58 |                 expect(callOrder).toEqual([
             |                                   ^
          59 |                     'process 2', 'callback 2',
          60 |                     'process 1', 'callback 1',
          61 |                     'process 4', 'callback 4',
      at AsyncQueue.q.drain (packages/loaders/test/AsyncQueue.tests.ts:58:35)
      at packages/loaders/src/base/AsyncQueue.ts:3812:15
      at onceWrapper (packages/loaders/src/base/AsyncQueue.ts:3448:12)
      at packages/loaders/test/AsyncQueue.tests.ts:21:21
```

https://github.com/pixijs/pixijs/runs/7199724543?check_suite_focus=true#step:8:685

**Comment by Nahdus** [comment]
Hi, had this same issue. I had multiple instance of electron running on task manager when this happened. I ended those and test run without this error

**Comment by bigtimebuddy** [comment]
I think this is a bad test that we should skip.

**Comment by GoodBoyDigital** [comment]
closing as v8 tests are pretty stable 👍
