### ISSUE TITLE
NineSlicePlane break from 6.3.2 > 6.4.2

### ISSUE THREAD

**Issue by Makio64** [pixijs/pixijs#8474]
### Expected Behavior
Code working in 6.3.2 work the same way in 6.4.2

### Current Behavior
this.bg = new NineSlicePlane(textureBackground, 40, 40, 40, 40) // should work fine

Current error when the nineSplice is render:
```
    at BatchSystem4.setObjectRenderer (GLFramebuffer.ts:45:30)
    at Mesh2._renderToBatch (resolveCharacters.ts:332:24)
    at Mesh2._render (resolveCharacters.ts:271:18)
    at SimplePlane2._render (pixi_js.js?v=b0919e93:47218:30)
    at Container5.render (Container.ts:635:18)
    at Container5.render (Container.ts:639:34)
    at Container5.render (Runner.ts:639:34)
    at Renderer4.render (index.ts:509:23)
    at Application2.render (index.ts:126:23)
    at TickerListener4.emit (TickerListener.ts:67:25)
```

### Steps to Reproduce
use NineSplice

### Environment

- **`pixi.js` version**: 6.4.2
- **Browser & Version**: All browsers latest
- **OS & Version**: _e.g. Window , Mac, iOS

**Comment by bigtimebuddy** [comment]
Works fine here: https://jsfiddle.net/bigtimebuddy/7qLm8hbr/

Please provide an example that reproduces the issue.

I suspect the issue is probably from upgrading (judging by all the numbers next to Container, Renderer, Mesh, etc). Please completely uninstall 6.3.2 before installing 6.4.2.

**Comment by Makio64** [comment]
Removing all pixi.js dep with `yarn remove xxx` and adding them back worked, thanks for  pointing in this direction !
