### ISSUE TITLE
@pixi/node - Assets doesn't support local Windows paths

### ISSUE THREAD

**Issue by Slynchy** [pixijs/pixijs#8564]
### Expected Behavior
Calling `Assets.load(path)` as detailed in the README file should load files as expected in the Node environment.

### Current Behavior
`Loader.load` fails to find a file that definitely exists, with the following error:
```
C:\Users\samly\Documents\Code\fake-foldername>ts-node test/brokenLoader.ts
PixiJS 6.5.1 - WebGL 1 - http://www.pixijs.com/
C:\Circle.png exists: true
C:\Users\samly\Documents\Code\fake-foldername\node_modules\@pixi\assets\src\loader\Loader.ts:147
                    throw new Error(`[Loader.load] Failed to load ${url}.\n${e}`);
                          ^
Error: [Loader.load] Failed to load /C:\Circle.png.
File not found: \C:\Circle.png
    at Loader.<anonymous> (C:\Users\samly\Documents\Code\fake-foldername\node_modules\@pixi\assets\src\loader\Loader.ts:147:27)
    at step (C:\Users\samly\Documents\Code\fake-foldername\node_modules\node_modules\tslib\tslib.es6.js:100:23)
    at Object.throw (C:\Users\samly\Documents\Code\fake-foldername\node_modules\node_modules\tslib\tslib.es6.js:81:53)
    at rejected (C:\Users\samly\Documents\Code\fake-foldername\node_modules\node_modules\tslib\tslib.es6.js:72:65)
```

### Steps to Reproduce
```
import { Application, Assets, Resource, Texture } from "@pixi/node";
import fs from "fs";

async function main() {
    await Assets.init();
    const app = new Application();
    const debugPath = `C:\\Circle.png`;

    console.log(`${
        debugPath
    } exists: ${
        fs.existsSync(debugPath) // true
    }`);

    const temp = await Assets.load(
        debugPath
    ) as Texture<Resource>; // crashes
}

main();
```

### Environment

- **`node` version**: v16.16.0
- **`npm` version**: 8.5.5
- **`pixi.js` version**: 6.5.1
- **Browser & Version**: n/a
- **OS & Version**: Windows 10

**Comment by bigtimebuddy** [comment]
I'd assume this is probably poor support for Windows pathing. Thanks for reporting.

**Comment by Slynchy** [comment]
A temporary workaround:

```
const PIXI = require("@pixi/node");
const crossFetch = require("cross-fetch");

PIXI.NodeAdapter.fetch = (url, options) => {
    const request = new crossFetch.Request(url, options);
    try {
        new crossFetch.URL(request.url);
        return fetch(url, request);
    }
    catch (error) {
        return new Promise((resolve, reject) => {
            const filePath = path.normalize(
                request.url.substring(1) // <=========== the important part
            ); 
            if (!fs.existsSync(filePath)) {
                reject(`File not found: ${filePath}`);
            }
            const readStream = fs.createReadStream(filePath);
            readStream.on('open', function () {
                resolve(new crossFetch.Response(readStream, {
                    url: request.url,
                    status: 200,
                    statusText: 'OK',
                    size: fs.statSync(filePath).size,
                    timeout: request.timeout
                }));
            });
        });
    }
}
```

Obviously not a good solution but good enough to unblock 😀
