### ISSUE TITLE
pixijs/node example crash (cannot find package '@pixi/loaders' )

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixijs#8693]
Copy/paste from the PixiJS/node example (https://github.com/pixijs/pixijs/blob/dev/bundles/pixi.js-node/README.md) results in a crash.

"@pixi/node": "^6.5.5",

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@pixi/loaders' imported from /Users/jensmalmborg/Projects/pixi-node/node_modules/@pixi/text-bitmap/dist/esm/text-bitmap.mjs
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:951:9)
    at moduleResolve (node:internal/modules/esm/resolve:1000:20)
    at defaultResolve (node:internal/modules/esm/resolve:1214:11)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'

**Comment by jnsmalm** [comment]
Got a bit further after installing both @pixi/loaders and @pixi/basis and also `brew install pkg-config cairo pango libpng jpeg giflib librsvg`.

Now instead I get:

Error: dlopen(/Users/jensmalmborg/Projects/pixi-node/node_modules/canvas/build/Release/canvas.node, 0x0001): symbol not found in flat namespace (_cairo_fill)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/jensmalmborg/Projects/pixi-node/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'ERR_DLOPEN_FAILED'

**Comment by jnsmalm** [comment]
Another guy was having the same issue, had to switch to Node 14.18.2. After that I got Cannot find package '@pixi/compressed-textures', so I installed that as well which Brough me a new error.

Now actually a PixiJS error:

PixiJS 6.5.5 - WebGL 1 - http://www.pixijs.com/
file:///Users/jensmalmborg/Projects/pixi-node/node_modules/@pixi/ticker/dist/esm/ticker.mjs:243
            this.lastTime = performance.now();
                            ^

ReferenceError: performance is not defined
    at Ticker._requestIfNeeded (file:///Users/jensmalmborg/Projects/pixi-node/node_modules/@pixi/ticker/dist/esm/ticker.mjs:243:29)
    at Ticker.start (file:///Users/jensmalmborg/Projects/pixi-node/node_modules/@pixi/ticker/dist/esm/ticker.mjs:381:18)
    at Application.start (file:///Users/jensmalmborg/Projects/pixi-node/node_modules/@pixi/ticker/dist/esm/ticker.mjs:670:27)
    at Application.TickerPlugin.init (file:///Users/jensmalmborg/Projects/pixi-node/node_modules/@pixi/ticker/dist/esm/ticker.mjs:690:18)
    at file:///Users/jensmalmborg/Projects/pixi-node/node_modules/@pixi/app/dist/esm/app.mjs:2822:25
    at Array.forEach (<anonymous>)
    at new Application (file:///Users/jensmalmborg/Projects/pixi-node/node_modules/@pixi/app/dist/esm/app.mjs:2821:30)
    at file:///Users/jensmalmborg/Projects/pixi-node/index.mjs:11:13

**Comment by bigtimebuddy** [comment]
@jnsmalm 

Could you try this:
https://github.com/bigtimebuddy/pixi-node-example

I'm running this with Node.js v16.16.0 and it works.

One thing I'm seeing about that example is that Application should do `{ autoStart: false }`, or we probably may want to remove the TickerPlugin for the Application. In this context, users should probably manage their own time/tick.

**Comment by jnsmalm** [comment]
Thanks, it worked after setting { autoStart: false }

**Comment by bigtimebuddy** [comment]
The global [performance](https://nodejs.org/api/globals.html#performance) was added in node.js v16. If you're trying to workaround in v14 and you need ticking, you can do this:

```js
import { performance } from 'perf_hooks';
globalThis.performance = performance;
```
