### ISSUE TITLE
syncUniforms stopped working on Chrome Dev channel

### ISSUE THREAD

**Issue by hdemmer** [pixijs/pixijs#8696]
Hey everyone! I'm trying to trace down a change in Chrome that causes my global uniforms to no longer work.
What I'm doing: I'm adding matrices as 16-entry arrays to `renderer.globalUniforms` for 3D stuff. In the past this worked just fine, but it broke in Chrome Canary and now also in the Chrome Dev channel.

The error is of the form:
```
TypeError: Cannot read properties of undefined (reading '17')
    at ShaderSystem2.syncUniforms (ShaderSystem.ts:152:32)
    at ShaderSystem2.syncUniformGroup (ShaderSystem.ts:140:18)
    at eval (eval at generateUniformsSync (generateUniformsSync.ts:269:12), <anonymous>:11:41)
```
Somehow the code-generation for syncing uniforms is different (?) on Chrome 108 causing the array to be interpreted as a UniformGroup, causing the above error.

I briefly tried the latest 6.x version of pixi and the error happened there as well.

Before embarking on building a repro case, I wanted to see if others have noticed issues with uniforms on the Chrome Dev channel. Also, I'd be grateful for pointers regarding correct use of globalUniforms, as I couldn't find anything in the docs and I don't understand the source well enough yet.

### Environment

- **`pixi.js` version**: 6.5.1
- **Browser & Version**: works in Chrome 105 and 106, also in Firefox, but is broken in Chrome 108
- **OS & Version**: Windows 10

**Comment by joel-Yolted** [comment]
Having the same issue after updating from 6.3.* to 6.5.7 but its occuring in Chrome 1.0.6.
Legacy code so still trying to make a repro, but it does appear to be some form of regression with 6.5

**Comment by bigtimebuddy** [comment]
Can someone make a simple reproduction?

**Comment by joel-Yolted** [comment]
I'm not 100% sure  my issue is related to this one, but it happens with ParticleContainer and using filters (wierdly enough not on the particle container)

small repro repo here: https://github.com/joel-Yolted/pixi-8696-repro

Stack trace:

`VM164:11 Uncaught TypeError: Cannot read properties of undefined (reading 'location')
    at eval (eval at generateUniformsSync (core.mjs:5833:1), <anonymous>:11:56)
    at ShaderSystem.syncUniforms (core.mjs:7787:1)
    at ShaderSystem.syncUniformGroup (core.mjs:7776:1)
    at eval (eval at generateUniformsSync (core.mjs:5833:1), <anonymous>:39:41)
    at ShaderSystem.syncUniforms (core.mjs:7787:1)
    at ShaderSystem.syncUniformGroup (core.mjs:7776:1)
    at ShaderSystem.bind (core.mjs:7753:1)
    at ParticleRenderer.render (particle-container.mjs:451:1)
    at ParticleContainer.render (particle-container.mjs:164:1)
    at Container.render (display.mjs:2162:1)`
    
  If you comment out the MotionBlur filter it does not trigger.

**Comment by SuperSodaSea** [comment]
@joel-Yolted I checked carefully and found that it seems to be a dependency problem. I look into the webpack bundle file and found that webpack is using the `cjs` version of `@pixi/filter-motion-blur`, causing both `cjs` and `esm` versions of `@pixi/core` in the bundle.
PixiJS's `Program` use a global `UID` to identify the program, and since there are two versions of `@pixi/core` in the bundle, there are also two different `UID`s in the bundle. This can lead to two `Program` having the same `id`, causing the error you see.

https://github.com/pixijs/pixijs/blob/55e5e0da83f7771eb2a85033fb03898319a2c346/packages/core/src/shader/Program.ts#L75

![image](https://user-images.githubusercontent.com/8724868/199890095-cb1836bc-fc58-4e65-9bc0-de511b04d102.png)

The error seems to be disappeared after removing the `exports` field in `@pixi/filter-motion-blur`'s `package.json` (which is introduced in pixijs/filters#337 before 4.2.0): `cjs` version is no more used, and the bundle is much smaller, but I have no idea why.
@bigtimebuddy Do you have any idea about this?

https://github.com/pixijs/filters/blob/v4.2.0/filters/motion-blur/package.json#L9-L15

![image](https://user-images.githubusercontent.com/8724868/199890270-f9d414fc-4f9d-45d7-9109-c5eb702a04af.png)

---

By the way, I think this problem is probably different from @hdemmer's problem, since this problem can happen on any browser, not only Chrome 108+.

**Comment by SuperSodaSea** [comment]
@hdemmer For your original problem, I can only reproduce a similar error with `renderer.globalUniforms.uniforms.test = { group: new Float32Array(16) }` (the name `group` is important, and the name `test` can be replaced by any other name), but the error happens not only on Chrome 108+ but on all browsers. Can you give more information on how you modify `globalUniforms`?

**Comment by joel-Yolted** [comment]
Thanks! @SuperSodaSea Ill see if i can apply the same workaround or just fork that filter.
