### ISSUE TITLE
Assets bundle load exception

### ISSUE THREAD

**Issue by vpmedia** [pixijs/pixijs#8733]
### Expected Behavior

Assets load successfully (works with v7.0.0-alpha.2)

### Current Behavior

`
   Loader.ts:148 Uncaught (in promise) Error: [Loader.load] Failed to load http://localhost:3000/asset/.....
   RangeError: Maximum call stack size exceeded

    at Loader.ts:148:1

    at async Promise.all (:3000/index 1)

    at async Loader.load (Loader.ts:153:1)

    at async AssetsClass._mapLoadToResolve (Assets.ts:676:1)

    at async Promise.all (:3000/index 0)

    at async AssetsClass.loadBundle (Assets.ts:545:1)

    at async ......
`

### Possible Solution

Downgrade to v.7.0.0-alpha.2

### Steps to Reproduce

`
  await Assets.init({ manifest: "/manifest.json" });
  await Assets.loadBundle("BundleName");
`

### Environment

- **`pixi.js` version**: v7.0.0-beta.3
- **Browser & Version**: Version 106.0.5249.119 (Official Build) (x86_64) (Same issue using Safari, Chrome, Firefox)
- **OS & Version**: MacOS Monterey 12.6
- **Running Example**: _url_

**Comment by SuperSodaSea** [comment]
What is the content of your `manifest.json`?

**Comment by SuperSodaSea** [comment]
Sorry, but I failed to reproduce this... Can you provide more information, such as find the line with `[Loader.load] Failed to load` in the bundle file you are using, and add a `console.log(e)` before it to see the real stack trace of the error?

https://github.com/pixijs/pixijs/blob/5823bec73949aba4c43609a53561c006af7f2517/packages/assets/src/loader/Loader.ts#L147-L148

**Comment by vpmedia** [comment]
If I remove the bundle loading and add one simple
`Assets.add(..) .. Assets.load(..) ..` the same exception is thrown, so it's not connected to the assets bundle format.
I'm having hard time figuring out how to modify the source in the node_modules folder, there is a bunch of package formats (pixi/assets, pixi.js, pixijs.legacy with cjs, esm subfolders).
I'm using create-react-app/webpack to compile my app..

But the thrown exception is re-thrown the way I see `.\n${e}` ..

**Comment by SuperSodaSea** [comment]
I tried `await Assets.init({ manifest: "/manifest.json" }); await Assets.loadBundle("BundleName");` using <script> elememt and using webpack, both of them work just fine.

The stack trace of the exception is for the line ```throw new Error(`[Loader.load] ...`)```, not for the inner RangeError `e`, so I have no idea what is really happening. If you can't figure out which file to modify, you can just edit the webpack output .js file.

**Comment by vpmedia** [comment]
I've created a Parcel compiled version which works, so the issue is connected to Create-React-App/Webpack.. I'm using React as an overlay UI for my Pixi.js app so this is an advanced use case, what is weird that with the v7-alpha everything was working fine..

**Comment by vpmedia** [comment]
Here is the stacktrace:

`RangeError: Maximum call stack size exceeded
    at Array Iterator.next (<anonymous>)
    at r (ImageBitmapResource.ts:59:5)
    at r (ImageBitmapResource.ts:59:5)
    at r (ImageBitmapResource.ts:59:5)
    at r (ImageBitmapResource.ts:59:5)
    at r (ImageBitmapResource.ts:59:5)
    at r (ImageBitmapResource.ts:59:5)
    at r (ImageBitmapResource.ts:59:5)
    at r (ImageBitmapResource.ts:59:5)
    at r (ImageBitmapResource.ts:59:5)`

**Comment by SuperSodaSea** [comment]
Ok, at least now we know that it may has something to do with the modification on `ImageBitmapResource`. I'll try Create-React-App later.

**Comment by vpmedia** [comment]
Thanks, maybe it's connected to WebWorkers which has been added since the alpha version..

**Comment by vpmedia** [comment]
Thanks! I've removed my dependency from create-react-app and started to use just webpack configurations,, much simplier and cleaner anyways..

**Comment by vpmedia** [comment]
I think you can close the issue as won't fix, maybe mention in the docs before releasing v7 that create-react-app is not supported, it depends on a bunch of packages and does a lot of tweaking (as far as I've reviewed an ejected app) so it's better to use webpack directly.

**Comment by bigtimebuddy** [comment]
Thanks for tracking this down @vpmedia. Also, create-react-app probably could get a bug report about this since it's like a transpiling error. I'd assume it's pretty easy to produce with similar class-inheritance, conditional super call.
