### ISSUE TITLE
Bug: `@pixi/node` cannot auto-detect renderer

### ISSUE THREAD

**Issue by StanFlint** [pixijs/pixijs#9032]
### Current Behavior

When following the example included in the `@pixi/node` readme (https://github.com/pixijs/pixijs/blob/dev/bundles/pixi.js-node/README.md), this error persists.

```
/usr/src/app/node_modules/@pixi/core/src/autoDetectRenderer.ts:67
    throw new Error('Unable to auto-detect a suitable renderer.');
          ^
Error: Unable to auto-detect a suitable renderer.
    at Object.autoDetectRenderer (/usr/src/app/node_modules/@pixi/core/src/autoDetectRenderer.ts:67:11)
    at new _Application (/usr/src/app/node_modules/@pixi/app/src/Application.ts:104:25)
```

### Expected Behavior

The Application should be able to initialise.

When I try to instantiate JUST the renderer with `const renderer = new Renderer()` I get
```
/usr/src/app/node_modules/@pixi/node/src/adapter/NodeCanvasElement.ts:182
                const _getUniformLocation = ctx.getUniformLocation;
                                                ^
TypeError: Cannot read properties of null (reading 'getUniformLocation')
    at NodeCanvasElement.getContext (/usr/src/app/node_modules/@pixi/node/src/adapter/NodeCanvasElement.ts:182:49)
    at Object.getTestContext (/usr/src/app/node_modules/@pixi/core/src/shader/utils/getTestContext.ts:28:26)
    at Object.getMaxFragmentPrecision (/usr/src/app/node_modules/@pixi/core/src/shader/utils/getMaxFragmentPrecision.ts:11:20)
    at new Program (/usr/src/app/node_modules/@pixi/core/src/shader/Program.ts:102:92)
    at Function.from (/usr/src/app/node_modules/@pixi/core/src/shader/Program.ts:147:43)
    at Function.from (/usr/src/app/node_modules/@pixi/core/src/shader/Shader.ts:106:33)
    at new ParticleRenderer (/usr/src/app/node_modules/@pixi/particle-container/src/ParticleRenderer.ts:109:30)
    at PluginSystem.init (/usr/src/app/node_modules/@pixi/core/src/plugin/PluginSystem.ts:88:31)
    at /usr/src/app/node_modules/@pixi/core/src/system/SystemManager.ts:134:33
    at Array.forEach (<anonymous>)
```

### Steps to Reproduce

This is reproduced by following the example provided in the readme (https://github.com/pixijs/pixijs/blob/dev/bundles/pixi.js-node/README.md)

The exact line which cases the error is
```
const app = new Application()
```

### Environment

This is running in a Docker container
- All of the required dependencies from [gl](https://www.npmjs.com/package/gl/v/4.5.3-win64.0#system-dependencies) and [canvas](https://www.npmjs.com/package/canvas#compiling) have been installed
- **`pixi.js` version: 7.0.5**
- **Browser & Version: NodeJS using `@pixi/node`**
- **OS & Version**: *e.g. Ubuntu 22.04*

**Comment by bigtimebuddy** [comment]
Have you installed xvfb? That is needed, for instance, when we run it on GitHub Actions.

**Comment by StanFlint** [comment]
Thank you very much! After a bit more finagling I got that working great. 

Should I add a couple lines about that in the readme? The existing resources there on installing `canvas` and `gl` are great it would be good to add another section about `xvfb`?

**Comment by bigtimebuddy** [comment]
I think some more readme context would be great, especially setting up for headless environments like docker. If you can even create a recipe or docs for using docker, that'd be awesome! I'm sure other users would find this helpful.

**Comment by StanFlint** [comment]
Yeah would be happy to do a write up of that. Where would be the best place to write that? In the readme, a separate .md file?

**Comment by bigtimebuddy** [comment]
Probably readme is a good place. Thank you for being willing to help!

**Comment by SuperSodaSea** [comment]
> <https://github.com/pixijs/pixijs/blob/dev/bundles/pixi.js-node/README.md#setup>

**Comment by StanFlint** [comment]
Not a problem, I will get on that 👍

**Comment by arjunbhatt670** [comment]
pixi is not utilizing GPU in docker container. I have Nvidia tesla T4 with drivers installed and detecting.
With xvfb, pixi uses WebGl renderer but runs very slow. Appreciate any help here.
