### ISSUE TITLE
Bug: Loading aliases, unloading them, setting new aliases and then reloading textures and using them will produce an error

### ISSUE THREAD

**Issue by Giacom** [pixijs/pixijs#9109]
### Current Behavior

When you load a texture, unload it and then load it again it will cause an error when trying to use it for a Sprite.

```ts
const app = new PIXI.Application({ background: '#1099bb', hello: true });
document.body.appendChild(app.view);

// Add the assets to load
PIXI.Assets.add('flowerTop', 'examples/assets/flowerTop.png');
PIXI.Assets.add('eggHead', 'examples/assets/eggHead.png');

const assets = ['flowerTop', 'eggHead'];

async function go() {
  
  const textures = await PIXI.Assets.load(assets);
  
  await PIXI.Assets.unload(assets)

  PIXI.Assets.add("flowerTop", "examples/assets/bunny.png");
  PIXI.Assets.add("eggHead", "examples/assets/bunny.png");

  {
    const myTextures = await PIXI.Assets.load(array);

    console.log(myTextures);
    const flower = PIXI.Sprite.from(myTextures.bunny);
    flower.anchor.set(0.5);
    flower.x = app.screen.width * 0.25;
    flower.y = (app.screen.height / 2) + 100;
    app.stage.addChild(flower);

    const egg = PIXI.Sprite.from(myTextures.bunny);
    egg.anchor.set(0.5);
    egg.x = app.screen.width * 0.75;
    egg.y = (app.screen.height / 2) + 100;
    app.stage.addChild(egg);
  }

}

go();
```

Instead you get this error message:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_pixiId')
    at Texture.from (Texture.mjs:128:19)
    at Sprite.from (Sprite.mjs:190:66)
    at go (demo.js:23:32)
```

### Expected Behavior

Should be able to use the new texture without any problems.

### Steps to Reproduce

1. Open https://www.pixiplayground.com/#/edit/TEmwE_ExPjqNlkr-NboRO
2. Check console log and check the error:

### Environment

- **`pixi.js` version**: *7.1.1*
- **Browser & Version**: *MS Edge*
- **OS & Version**: *Windows 11*
- **Running Example**: *https://www.pixiplayground.com/#/edit/TEmwE_ExPjqNlkr-NboRO*

**Comment by SuperSodaSea** [comment]
```diff
- const flower = PIXI.Sprite.from(myTextures.bunny);
+ const egg = PIXI.Sprite.from(myTextures.flowerTop);

- const egg = PIXI.Sprite.from(myTextures.bunny);
+ const egg = PIXI.Sprite.from(myTextures.eggHead);
```

Also it is invalid to add a key again, as the warning says:

```
[Resolver] already has key: flowerTop overwriting
[Resolver] already has key: eggHead overwriting
```

If you really want to set a key again, try `PIXI.Assets.reset()`.

**Comment by Giacom** [comment]
Is there a way to reset just a specific alias?

**Comment by SuperSodaSea** [comment]
> Is there a way to reset just a specific alias?

It looks like there's no way to do that right now. You are welcome to create a [Feature Request](https://github.com/pixijs/pixijs/issues/new?assignees=&labels=Feature+Request&template=feature_request.yml&title=Feature+Request%3A+) for this.

**Comment by Giacom** [comment]
Thanks, I just made one for it [here](https://github.com/pixijs/pixijs/issues/9115).

Closing this issue.
