### ISSUE TITLE
Bug: Creating a PIXI.Renderer() with an OffscreenCanvas in a worker fails due to internal access of `document`

### ISSUE THREAD

**Issue by dxinteractive** [pixijs/pixijs#9421]
### Current Behavior

I've observed passing an `OffscreenCanvas()` as the `view`  of a `PIXI.Renderer({ view })` appears to error out, as `document` is accessed but is not defined in a worker context.

```
-pixijs-bunnies-worker.worker.d6d793b8.js:15208 Uncaught (in promise) ReferenceError: document is not defined
    at new AccessibilityManager (06-pixijs-bunnies-worker.worker.d6d793b8.js:15208:19)
    at PluginSystem.init (06-pixijs-bunnies-worker.worker.d6d793b8.js:8577:28)
    at Runner.emit (06-pixijs-bunnies-worker.worker.d6d793b8.js:3182:24)
    at StartupSystem.run (06-pixijs-bunnies-worker.worker.d6d793b8.js:9214:29)
    at new _Renderer (06-pixijs-bunnies-worker.worker.d6d793b8.js:10700:20)
    at renderBitmap (06-pixijs-bunnies-worker.worker.d6d793b8.js:23157:22)
    at 06-pixijs-bunnies-worker.worker.d6d793b8.js:23176:26
A
``` 

### Expected Behavior

`document` should not be accessed in a worker context, so we can use offscreen rendering in a worker as described [here](https://github.com/pixijs/pixijs/issues/4538#issuecomment-1315380221).

Perhaps `AccessibilityManager` isn't really even required in a worker context, but I am not familiar enough with Pixi.js internal to say.

### Steps to Reproduce

Go here to see error: https://dxinteractive.github.io/pixijs-experiments/#/pixijs-bunnies-worker
Source: https://github.com/dxinteractive/pixijs-experiments/blob/main/src/experiments/06-pixijs-bunnies-worker.tsx
Source (worker): https://github.com/dxinteractive/pixijs-experiments/blob/main/src/experiments/06-pixijs-bunnies-worker.worker.ts

### Environment

- **`pixi.js` version**: 7.2.4
- **Browser & Version**: Chrome 112
- **OS & Version**: MacOS Venture 13.3
- **Running Example**: https://dxinteractive.github.io/pixijs-experiments/#/pixijs-bunnies-worker

### Additional Information

If you have any ideas why this occurs, please let me know, thanks!

**Comment by SuperSodaSea** [comment]
You need to use package `@pixi/webworker` in the worker instead of `pixi.js`.

**Comment by dxinteractive** [comment]
Ok that's good news, thanks @SuperSodaSea ! Is there somewhere that this is documented? I'm happy to help improve the docs if not.

- https://pixijs.io/examples/#/offscreen-canvas/web-worker.js doesn't mention that a different package must be used,
- none of the issues talking about this feature make explicit mention that `@pixi/webworker` should be used (although I can see a link to a PR with the package name in the title now)
- the search in the sidebar of https://pixijs.download/release/docs/index.html shows no results for "worker" or "webworker"

So perhaps this is a discovery problem.

**Comment by SuperSodaSea** [comment]
Yeah we do need to give more details in the documentation. Maybe we can add information in [README.md](https://github.com/pixijs/pixijs/blob/5f6b33536dfd4a610e97d4bf94c2b86663e36eb7/README.md), [bundles/pixi.js/README.md](https://github.com/pixijs/pixijs/blob/5f6b33536dfd4a610e97d4bf94c2b86663e36eb7/bundles/pixi.js/README.md), and add a new page in [PixiJS Guides](https://github.com/pixijs/guides). PR is welcomed!

**Comment by DutchKevv** [comment]
How do you pass mouse events to the worker, so that pixi-viewport etc works? 

Do you have to manually trigger a mouse-event and keep track of it between main->worker? Thanks

**Comment by bigtimebuddy** [comment]
@DutchKevv this is unsupported currently (pointer/touch/mouse events + worker rendering), but welcome anyone that wants to tackle this issue.

**Comment by JeanLouisMassei** [comment]
+1 for the issue.

Yet here is the solution : 

index.html
const canvas = document.createElement('canvas');
document.body.appendChild(canvas);
const view = canvas.transferControlToOffscreen();
const worker = new Worker('./worker.js');
worker.postMessage({where:view}, [view]);

worker.js
self.importScripts("https://cdn.jsdelivr.net/npm/@pixi/webworker@7.2.4/dist/webworker.min.js");

self.onmessage = function(args)
{
    const app = new PIXI.Application({ 
        width:500,
        height:500,
        view:args.data.where
    });

    const container = new PIXI.Container();
}

**Comment by Zyie** [comment]
Hi there! 👋

We're doing some housekeeping and closing out older issues that haven't had recent activity.

PixiJS has evolved significantly since this issue was opened. If you're still experiencing this issue on PixiJS v8 (latest), please open a new issue with updated details and a minimal reproduction case.

Thanks for your understanding and for helping us keep the issue tracker focused and maintainable! 🩷
