### ISSUE TITLE
Bug:TypeError t.isInteractive comes with version 7.2.4

### ISSUE THREAD

**Issue by munasinghecm** [pixijs/pixijs#9495]
### Current Behavior

I'm getting the following error when I hover my mouse over any area after rendering Pixijs to the HTML element. Though when I downgrade the Pixijs version to 7.1.2 this issue disappeared. No other issues but it's continuously logged in the console log.
`ERROR TypeError: t.isInteractive is not a function
    at Na.hitTestMoveRecursive (node_modules\pixi.js\dist\pixi.min.js:869:7430)
    at Na.hitTestMoveRecursive (node_modules\pixi.js\dist\pixi.min.js:869:7127)
    at Na.hitTestMoveRecursive (node_modules\pixi.js\dist\pixi.min.js:869:7127)
    at Na.hitTestMoveRecursive (node_modules\pixi.js\dist\pixi.min.js:869:7127)
    at Na.hitTest (node_modules\pixi.js\dist\pixi.min.js:869:5719)
    at Na.createPointerEvent (node_modules\pixi.js\dist\pixi.min.js:869:15349)
    at Na.mapPointerMove (node_modules\pixi.js\dist\pixi.min.js:869:9674)
    at Na.mapEvent (node_modules\pixi.js\dist\pixi.min.js:869:5595)
    at yn.onPointerMove (node_modules\pixi.js\dist\pixi.min.js:869:20559)
    at ZoneDelegate.invokeTask (zone.js:406:1)`

### Expected Behavior

The error should be disappeared 

### Steps to Reproduce

Render pixijs app to a HTML element

### Environment

- **`pixi.js` version**: *e.g. 7.2.4*
- **Browser & Version**: *e.g. Chrome 114.0.5735.134 *
- **OS & Version**: *e.g. Windows 11*

### Possible Solution

No solution can be found, though the issue is not available in Pixijs version 7.1.4

**Comment by bigtimebuddy** [comment]
Can you please provide a live reproduction of this issue (e.g., codepen, codesandbox, jsfiddle, pixiplayground)?

**Comment by munasinghecm** [comment]
@bigtimebuddy I tested with the code and was finally able to find out a solution for the issue. The issue was there with images I get for the Pixijs application as well. So I added 
`this.pixiApp.stage.eventMode = 'none';` 
before extracting the image using the `renderer.extract.image()` method. With that, the issue was sorted out though this concern was not available in 7.1.2
Although I have a few concerns regarding image creation as well. Why the Pixijs elements are available with the image I extracted using the `renderer.extract.image()`.

**Comment by CosmoMyzrailGorynych** [comment]
I'm getting that when there are particles from @pixi/particle-emitter on-screen and a user moves their pointer.

**Comment by CosmoMyzrailGorynych** [comment]
@bigtimebuddy I did made a repro on codepen but it kills the browser even if you have just one particle in a second :/ couldn't save it. But,

The error shows every frame for every particle for every pointer event, like mouse movement.

I used a ESBuild of PIXI.js v7.3.2 with [particle-emitter](https://github.com/pixijs/particle-emitter/) as PIXI.particles property, and the code below. (The example script of particle-emitter with lowered spawn frequency and an image.) This should be easy to replicate locally.
 
<details><summary>JS Code</summary>
<p>

```js
const app = new PIXI.Application();
const versions = document.createElement('div');
versions.innerHTML = `Pixi.js: ${PIXI.VERSION}, particle-emitter: 5.0.8 (static; don't have a variable for that)`;
document.body.appendChild(versions);
document.body.appendChild(app.view);

var emitter = new PIXI.particles.Emitter(
    // The PIXI.Container to put the emitter in
    // if using blend modes, it's important to put this
    // on top of a bitmap, and not use the root stage Container
    app.stage,
    // Emitter configuration, edit this to change the look
    // of the emitter
    {
        lifetime: {
            min: 0.5,
            max: 0.5
        },
        frequency: 0.5,
        spawnChance: 1,
        particlesPerWave: 1,
        maxParticles: 1000,
        pos: {
            x: 0,
            y: 0
        },
        addAtBack: false,
        behaviors: [
            {
                type: 'alpha',
                config: {
                    alpha: {
                        list: [
                            {
                                value: 0.8,
                                time: 0
                            },
                            {
                                value: 0.1,
                                time: 1
                            }
                        ]
                    }
                }
            },
            {
                type: 'scale',
                config: {
                    scale: {
                        list: [
                            {
                                value: 1,
                                time: 0
                            },
                            {
                                value: 0.3,
                                time: 1
                            }
                        ]
                    }
                }
            },
            {
                type: 'color',
                config: {
                    color: {
                        list: [
                            {
                                value: 'fb1010',
                                time: 0
                            },
                            {
                                value: 'f5b830',
                                time: 1
                            }
                        ]
                    }
                }
            },
            {
                type: 'moveSpeed',
                config: {
                    speed: {
                        list: [
                            {
                                value: 200,
                                time: 0
                            },
                            {
                                value: 100,
                                time: 1
                            }
                        ],
                        isStepped: false
                    }
                }
            },
            {
                type: 'rotationStatic',
                config: {
                    min: 0,
                    max: 360
                }
            },
            {
                type: 'spawnShape',
                config: {
                    type: 'torus',
                    data: {
                        x: 0,
                        y: 0,
                        radius: 10
                    }
                }
            },
            {
                type: 'textureSingle',
                config: {
                    texture: PIXI.Texture.from('https://avatars.githubusercontent.com/u/5406849?s=48&v=4')
                }
            }
        ]
    }
);

// Calculate the current time
var elapsed = Date.now();

// Update function every frame
var update = function () {
    // Update the next frame
    requestAnimationFrame(update);

    var now = Date.now();

    // The emitter requires the elapsed
    // number of seconds since the last update
    emitter.update((now - elapsed) * 0.001);
    elapsed = now;
};

// Start emitting
emitter.emit = true;

// Start the update
update();
```

</p>
</details> 


As this error does not appear in pixi.js v7.2.2 but does show up on pixi.js v7.3.2, I consider it a breaking change in a minor version bump of pixi.js and thus a bug of pixi.js. This also seems the same root issue OP has faced, as updating/rollbacking shows same behavior. If you believe in the opposite, tell me and I will file the issue at particle-emitter.

**Comment by ryuuzako** [comment]
hi, this happens to me too i guess?
```
Uncaught TypeError: currentTarget.isInteractive is not a function
    at EventBoundary.hitTestMoveRecursive (EventBoundary.mjs:150:1)
    at EventBoundary.hitTestMoveRecursive (EventBoundary.mjs:134:1)
    at EventBoundary.hitTestMoveRecursive (EventBoundary.mjs:134:1)
    at EventBoundary.hitTestMoveRecursive (EventBoundary.mjs:134:1)
    at EventBoundary.hitTestMoveRecursive (EventBoundary.mjs:134:1)
    at EventBoundary.hitTest (EventBoundary.mjs:65:1)
    at EventBoundary.createPointerEvent (EventBoundary.mjs:460:1)
    at EventBoundary.mapPointerMove (EventBoundary.mjs:273:1)
    at EventBoundary.mapEvent (EventBoundary.mjs:52:1)
    at _EventSystem2.onPointerMove (EventSystem.mjs:114:1)
```

it is also solved by setting the event mode on the particle container to none; it is always triggered on a Particle object, not on other objects.

    "@pixi/particle-emitter": "^5.0.8",
    "pixi-spine": "^4.0.4",
    "pixi.js": "^7.4.2"
