### ISSUE TITLE
Bug: change graphics.geometry.points, error Cannot find propagation path to disconnected target

### ISSUE THREAD

**Issue by xiao-zhuge** [pixijs/pixijs#9523]
### Current Behavior

1. use PIXI.Graphics create a curve
2. change graphics.geometry.points, this curve  has not be refreshed
3. I call graphics.geometry.invalidate(),but It seems useless；
4. I call renderer.render(curve), This achieved the effect I wanted，but the following error will be reported 
**This error occurred randomly**
EventBoundary.mjs:119 Uncaught Error: Cannot find propagation path to disconnected target
    at EventBoundary.propagationPath (EventBoundary.mjs:119:1)
    at FederatedPointerEvent.composedPath (FederatedEvent.mjs:38:1)
    at EventBoundary.propagate (EventBoundary.mjs:82:1)
    at EventBoundary.dispatchEvent (EventBoundary.mjs:55:1)
    at EventBoundary.mapPointerMove (EventBoundary.mjs:286:1)
    at EventBoundary.mapEvent (EventBoundary.mjs:65:1)
    at _EventSystem.onPointerMove (EventSystem.mjs:129:1)

### Expected Behavior

I want to modify the position of the points to update the curve

### Steps to Reproduce

1. use PIXI.Graphics create a curve
2. change graphics.geometry.points, this curve  has not be refreshed
3. I call graphics.geometry.invalidate(),but It seems useless；
4. I call renderer.render(curve), This achieved the effect I wanted，but the following error will be reported 

### Environment

- **`pixi.js` version**: *e.g. 7.2.4*

**Comment by xiao-zhuge** [comment]
I use pixi-viewport to perform scene scaling and other operations

**Comment by blnvdanil** [comment]
This seems to be related to your `renderer.render(graphics)` call, as far as I can tell, you had a Viewport container rendered before that call, and it seems to be a problem, maybe mousemove event is fired before you rendered your graphics, but processed after, and because of that it can not find a path from target to root

I am not an expert by the way, that just an assumption

**Comment by SignDawn** [comment]
graphics.geometry is getter ，Maybe it shouldn't have been modified。

Why not clear and redraw ?

**Comment by IamRaduB** [comment]
I have a Vue3 project with PixiJS and I encountered the same error. My issue was that I was keeping the pixi application instance inside a `ref`. The reference to the app might have been lost along the way, possibly due to forgetting to add `.value` to the ref to access the actual value.
The fix though was just storing the pixi app instance inside a normal variable and passing it along from there.

**Comment by Zyie** [comment]
Thanks for reporting this issue!

We haven’t received a minimal reproduction to help investigate, and since some time has passed, we’re going to close this for now to help keep the issue tracker focused.

Please feel free to open a new issue with a minimal example, and we’d be happy to take another look
