### ISSUE TITLE
Bug: Getting the height "Text" container with empty value gives an uncaught error

### ISSUE THREAD

**Issue by NotAmaan** [pixijs/pixijs#9660]
### Current Behavior

Adding a "Text" container with an empty string provided to options.text works fine.
But if you `get` its `height`, it causes the following error:

```
resolveCharacters.ts:54 Uncaught Error: [BitmapFont]: Empty set when resolving characters.
    at resolveCharacters (resolveCharacters.ts:54:15)
    at DynamicBitmapFont.ensureCharacters (DynamicBitmapFont.ts:79:26)
    at BitmapFontManagerClass.getFont (BitmapFontManager.ts:77:44)
    at BitmapFontManagerClass.getLayout (BitmapFontManager.ts:84:33)
    at BitmapFontManagerClass.measureText (BitmapFontManager.ts:91:21)
    at _TextView._updateBounds (TextView.ts:191:57)
    at get bounds [as bounds] (TextView.ts:133:18)
    at _TextView.addBounds (TextView.ts:142:30)
    at getLocalBounds (getLocalBounds.ts:23:21)
    at get height [as height] (measureMixin.ts:44:40)
```

### Expected Behavior

Shouldn't cause uncaught error

### Steps to Reproduce

- Create a new Text
```
this.#foo = new Text({
  text: '',
  renderMode: 'bitmap',
});
```
- Access the height of the text instance
`console.log(this.#foo.height);`

### Environment

- **`pixi.js` version**: *v8.0.0-alpha.3*
- **Browser & Version**: *Chrome*
- **OS & Version**: *MacOS*

**Comment by Zyie** [comment]
fixed #9662
