### ISSUE TITLE
Bug: unsafe-eval not patched in @pixi/webworker 7.3.1

### ISSUE THREAD

**Issue by ameyms** [pixijs/pixijs#9766]
### Current Behavior

Thanks for building PIXI! 

I am using `@pixi/webworker` `7.3.1`. However I am seeing this error:

```

918.29cecab6.chunk.js:2 Uncaught Error: Current environment does not allow unsafe-eval, please use @pixi/unsafe-eval module to enable support.
    at t.value (918.29cecab6.chunk.js:2:185319)
    at new t (918.29cecab6.chunk.js:2:185131)
    at r.value (918.29cecab6.chunk.js:2:219629)
    at r.value (918.29cecab6.chunk.js:2:219355)
    at new r (918.29cecab6.chunk.js:2:88715)
```

### Expected Behavior

`@pixi/unsafe-eval` is deprecated: https://v2-pixijs.com/api/modules/pixi_unsafe_eval 

> Apply the no new Function patch to ShaderSystem in @pixi/core. @pixi/unsafe-eval is self-installed since 7.1.0, so this function no longer needs to be called manually.

So this error should not have occurred. 

### Steps to Reproduce

Unsure about exact steps. But I am guessing I am loading something from share system that requires unsafe eval?

### Environment

- **`@pixi/webworker` version**: *7.3.1*
- **Browser & Version**: *Version 118.0.5993.70 (Official Build) (arm64)*
- **OS & Version**: *macOS Ventura*

**Comment by SuperSodaSea** [comment]
`@pixi/unsafe-eval` itself is not deprecated, only `install()` is deprecated:

```js
import { install } from '@pixi/unsafe-eval';
install(); // Old usage before v7.1.0, deprecated now

import '@pixi/unsafe-eval'; // New usage, you still need to import it
```

**Comment by ameyms** [comment]
Thanks for your responses,  @bigtimebuddy @SuperSodaSea !

I have that import (`import '@pixi/unsafe-eval'`) now but it still failed with the same error.
Looking at `@pixi/unsafe-eval` code, it seems to be patching just `@pixi/core`. 

Is this sufficient even if I use `@pixi/webworker`?

**Comment by SuperSodaSea** [comment]
Some bundler configurations may cause this issue. Can you please provide a reproduction, so that we can figure out what the problem is?

**Comment by Zyie** [comment]
Thanks for reporting this issue!

We haven’t received a minimal reproduction to help investigate, and since some time has passed, we’re going to close this for now to help keep the issue tracker focused.

Please feel free to open a new issue with a minimal example, and we’d be happy to take another look
